== Math

=== Factorial

[latexmath]
++++
n! =
\begin{cases}
  1       & \text{if $(n = 0)$} \\
  n(n-1)! & \text{if $(n < 1)$}
\end{cases}
++++

* Using recursion
+
[source,haskell]
.src/math/fac.hs
----
-- Using pattern matching
facRecPm :: (Integral a) => a -> a
facRecPm 0 = 1
facRecPm n = n * facRecPm (n-1)

-- Using conditional guards
facRecCg :: (Integral a, Eq a) => a -> a
facRecCg n | n == 0    = 1
        | otherwise = n * facRecCg (n-1)

-- Using if-then-else
facRecIfThenElse :: (Integral a, Eq a) => a -> a
facRecIfThenElse n =
  if n == 0 then 1 else n * facRecIfThenElse (n-1)
----

* Using product
+
[source,haskell]
.A function that calculates the factorial of a natural number
----
Prelude> let fact n = product [1..n]
Prelude> fact 5
120
Prelude> fact 10
3628800
Prelude>
----

=== Fibonacci sequence

[source,haskell]
----
fib :: Int -> Int
fib 0 = 0
fib 1 = 1
fib n = fib(n-2) + fib(n-1)
----

=== Collatz map

[source,haskell]
.src/math/collatz_with_guards.hs
----
collatz :: Integer -> [Integer]
collatz n | n == 1         = [1]
          | n `mod` 2 == 0 = n : collatz (n `div` 2)
          | otherwise      = n : collatz (n * 3 + 1)
----

[source,haskell]
.src/math/collatz_with_pattern.hs
----
collatz :: Integer -> [Integer]
collatz 1 = [1]
collatz n | even n    = n : collatz (n `div` 2)
          | otherwise = n : collatz (n * 3 + 1)
----

=== Complex number

[source,haskell]
.src/math/complex.hs
----
import Data.Complex

cubed :: (RealFloat a) => Complex a -> Complex a
cubed x = x * x * x
----

[latexmath]
++++
\begin{aligned}
\omega &= \frac{-1 + \sqrt{3}i}{2} \\
\omega^{3} &= 1
\end{aligned}
++++

[source,haskell]
.float
----
*Main> let omega_f = ((-0.5)::Float) :+ 0.5 * sqrt(3)
*Main> :t (^)
(^) :: (Num a, Integral b) => a -> b -> a
*Main> omega_f ^ 3
1.0 :+ 0.0
*Main> omega_f * omega_f * omega_f
1.0 :+ 0.0
*Main> cubed omega_f
1.0 :+ 0.0
*Main> :t (**)
(**) :: Floating a => a -> a -> a
*Main> omega_f ** 3
1.0 :+ 1.7484555e-7
*Main> omega_f ** ((3::Float) :+ 0)
1.0 :+ 1.7484555e-7
----

[source,haskell]
----
*Main> let omega_d = ((-0.5)::Double) :+ 0.5 * sqrt(3)
*Main> :t (^)
(^) :: (Num a, Integral b) => a -> b -> a
*Main> omega_d ^ 3
0.9999999999999998 :+ 1.1102230246251565e-16
*Main> omega_d * omega_d * omega_d
0.9999999999999998 :+ 1.1102230246251565e-16
*Main> cubed omega_d
0.9999999999999998 :+ 1.1102230246251565e-16
*Main> :t (**)
(**) :: Floating a => a -> a -> a
*Main> omega_d ** 3
0.9999999999999997 :+ 6.432490598706544e-16
*Main> omega_d ** ((3::Double) :+ 0)
0.9999999999999997 :+ 6.432490598706544e-16
----
