ifndef::leveloffset[]
:toc: left
:toclevels: 3
:icons: font
endif::[]

== Haskell examples

=== ghci

[source,console]
----
$ ghci
GHCi, version 8.0.2: http://www.haskell.org/ghc/  :? for help
----

=== Type annotations

==== same types

[source,haskell]
----
Prelude> (+) 2 3 ::Double
5.0
----

==== different types

[source,haskell]
----
add_int_and_float :: Integer -> Float -> Float
add_int_and_float x y = fromIntegral(x) + y
main = do
    print(add_int_and_float 1 1.5)
----

.Results
* No type annotations
+
[source,haskell]
----
*Main> add_int_and_float 3 4.5
7.5
----

* NG: Both add type annotations as Integer
+
[source,haskell]
----
*Main> add_int_and_float 3 4.5 :: Integer

<interactive>:3:1: error:
    • Couldn't match expected type ‘Integer’ with actual type ‘Float’
    • In the expression: add_int_and_float 3 4.5 :: Integer
      In an equation for ‘it’: it = add_int_and_float 3 4.5 :: Integer
----

* Add type annotations as Float to right parameter
+
[source,haskell]
----
*Main> add_int_and_float 3 (4.5::Float)
7.5
----

* Add different type annotations to both variables
+
[source,haskell]
----
*Main> add_int_and_float (3::Integer) (4.5::Float)
7.5
----

==== String

===== Concatenate vector of chars into single string


* Chars
+
[source,haskell]
----
Prelude> ['a', 'b', 'c']
"abc"
----

* Using `:`

[source,haskell]
----
Prelude> 'a':'b':'c':[]
"abc"
----

===== Concatenate vector of strings into single string

* Using `(++)`
+
[source,haskell]
----
Prelude> :t (++)
(++) :: [a] -> [a] -> [a]
Prelude> "abc" ++ "123" ++ "cdf"
"abc123cdf"
Prelude>
----

* Using `concat`
+
[source,haskell]
----
Prelude> :t concat
concat :: Foldable t => t [a] -> [a]
Prelude> concat ["abc", "123", "cdf"]
"abc123cdf"
Prelude>
----

* Using `Control.Monad.join`
+
[source,haskell]
----
Prelude> Control.Monad.join ["abc", "123", "cdf"]
"abc123cdf"
----
+
[source,haskell]
----
Prelude> import Control.Monad
Prelude Control.Monad> join ["abc", "123", "cdf"]
"abc123cdf"
Prelude Control.Monad>
----

* You can also use the list monad to reduce the list to a single string, then re-wrap the result in a list.
+
[source,haskell]
----
Prelude> ["abc", "123", "cdf"] >>= id
"abc123cdf"
Prelude>
----

* using `foldr` and `foldl`
+
[source,haskell]
----
Prelude> foldr (\s_prepend s -> s_prepend ++ s) "" ["abc", "123", "cdf"]
"abc123cdf"
Prelude> foldl (\s s_add -> s ++ s_add) "" ["abc", "123", "cdf"]
"abc123cdf"
----

===== Join strings with a delimiter

* Using `Data.List.intercalate`
+
[source,haskell]
----
Prelude> Data.List.intercalate ", " ["John", "Due"]
"John, Due"
----
+
[source,haskell]
----
Prelude> import Data.List
Prelude Data.List> intercalate ", " ["John", "Due"]
"John, Due"
Prelude Data.List>
----

==== List

* Make a list
+
[source,haskell]
----
Prelude> [1, 2, 3]
[1,2,3]
Prelude> :t []
[] :: [t]
----
+
[source,haskell]
.Using the colon operator
----
Prelude> 1:2:3:[]
[1,2,3]
Prelude> :t (:)
(:) :: a -> [a] -> [a]
----

* Prepend the item to the list
+
.Using the colon operator. colon is the "prepend" operator
[source,haskell]
----
Prelude> 1:2:3:[]
[1,2,3]
Prelude> "apple":"banana":"cherry":["durian"]
["apple","banana","cherry","durian"]
----
+
----
Prelude> (:) 1 []
[1]
Prelude> (:) 1 ((:) 2 ((:) 3 []))
[1,2,3]
Prelude> (:) 1 $ (:) 2 $ (:) 3 []
[1,2,3]
Prelude> ((:) 1 . (:) 2 . (:) 3) []
[1,2,3]
----

* Returns the first item of a list
+
[source,haskell]
.Using `head`
----
Prelude> head []
*** Exception: Prelude.head: empty list
Prelude> head [1, 2, 3]
1
----
+
[source,haskell]
----
Prelude> let head' (h:_) = h
Prelude> :t head'
head' :: [t] -> t
Prelude> head' []
*** Exception: <interactive>:61:5-19: Non-exhaustive patterns in function head'

Prelude> head' [1, 2, 3]
1
Prelude> head' ["apple", "banana", "cherry", "durian"]
"apple"
----
+
[source,haskell]
.Using `take`
----
Prelude> take 1 []
[]
Prelude> take 1 [1, 2, 3]
[1]
----
+
[source,haskell]
.Using `foldr`
----
Prelude> foldr (\x _ -> [x]) [] []
[]
Prelude> foldr (\x _ -> [x]) [] [1, 2, 3]
[1]
Prelude> foldr (\s _ -> [s]) [] []
[]
Prelude> foldr (\s _ -> [s]) [] ["apple", "banana", "cherry", "durian"]
["apple"]
----

* returns the last item of a list
+
[source,haskell]
.Using `last`
----
Prelude> last [1, 2, 3]
3
----
+
[source,haskell]
.Using `foldl`
----
Prelude> foldl (\_ x -> x) 0 [1, 2, 3]
3
----

* it accepts a list and returns the list without its last item
+
[source,haskell]
----
Prelude> init [1, 2, 3]
[1,2]
----

* it accepts a list and returns the list without its first item
+
[source,haskell]
----
Prelude> tail ["A", "B", "C"]
["B","C"]
Prelude> drop 1 ["A", "B", "C"]
["B","C"]
----
+
[source,haskell]
----
Prelude> let tail' (_:t) = t
Prelude> :t tail'
tail' :: [t] -> [t]
Prelude> tail' []
*** Exception: <interactive>:67:5-19: Non-exhaustive patterns in function tail'

Prelude> tail' ["A", "B", "C"]
["B","C"]
----

* The length of a list
+
[source,haskell]
----
Prelude> :t length
length :: Foldable t => t a -> Int
Prelude> length ["apple", "banana", "cherry", "durian"]
4
----
+
[source,haskell]
.The length of a list without the "length" function in Haskell
----
Prelude> foldr (\_ n -> n + 1) 0 ["apple", "banana", "cherry", "durian"]
4
----

* Reverse a list in haskell
+
[source,haskell]
----
Prelude> reverse ["apple","banana","cherry"]
["cherry","banana","apple"]
----
+
[source,haskell]
----
Prelude> foldr (\x xs -> xs ++ [x]) [] ["apple", "banana", "cherry"]
["cherry","banana","apple"]
----

* Program to left rotate a list
+
[source,haskell]
----
Prelude> let rotate_l a = tail a ++ take 1 a
Prelude> :t rotate_l
rotate_l :: [a] -> [a]
Prelude> rotate_l [1, 2, 3]
[2,3,1]
Prelude> rotate_l $ rotate_l [1, 2, 3]
[3,1,2]
Prelude> rotate_l $ rotate_l $ rotate_l [1, 2, 3]
[1,2,3]
----

* Program to right rotate a list
+
[source,haskell]
----
Prelude> let rotate_r a = [last a] ++ init a
Prelude> :t rotate_r
rotate_r :: [a] -> [a]
Prelude> rotate_r [1, 2, 3]
[3,1,2]
Prelude> rotate_r $ rotate_r [1, 2, 3]
[2,3,1]
Prelude> rotate_r $ rotate_r $ rotate_r [1, 2, 3]
[1,2,3]
Prelude> rotate_l $ rotate_r [1, 2, 3]
[1,2,3]
----

==== List comprehension (リストの内包表記)

[source,haskell]
.3の倍数を抽出する
----
Prelude> [p | p <- [1..10], p `mod` 3 == 0]
[3,6,9]
Prelude> [1..10] >>= \x -> if x `mod` 3 == 0 then pure x else []
[3,6,9]
----

[source,haskell]
.Making a list of divisors in Haskell
----
Prelude> [x | x <- [2..9], 10 `mod` x == 0]
[2,5]
Prelude> [2..9] >>= \x -> if 10 `mod` x == 0 then pure x else []
[2,5]
----

[source,haskell]
.Find cubic root of a number
----
Prelude> [x | x <- [2..7], x * x * x == 8]
[2]
Prelude> [2..7] >>= \x -> if x * x * x == 8 then pure x else []
[2]
----

[source,haskell]
----
isPrime k = if k > 1 then null [ x | x <- [2..k - 1], k `mod` x == 0] else False
----

==== Tuples

* fst and snd
+
[source,haskell]
----
Prelude> fst(1, 2)
1
Prelude> snd(1, 2)
2
----

* swap
+
[source,haskell]
----
Prelude> import Data.Tuple
Prelude Data.Tuple> swap("hello", "world")
("world","hello")
Prelude Data.Tuple> swap $ swap("hello", "world")
("hello","world")
Prelude Data.Tuple> (swap . swap)("hello", "world")
("hello","world")
----

[source,haskell]
----
Prelude> curry fst "hello" "world"
"hello"
Prelude> uncurry div (10, 5)
2
Prelude>
----

=== Flow control statements

==== Loop using counter

* not using using guards
+
[source,haskell]
.loop_counter_no_guards.hs
----
main = do
    let loop 6 = return ()
        loop i = do
            print i
            loop (i + 1)
    loop 1
----
+
[source,haskell]
----
*Main> :load src/prelude/loop_counter_no_guards.hs
[1 of 1] Compiling Main             ( src/prelude/loop_counter_no_guards.hs, interpreted )
Ok, modules loaded: Main.
*Main> main
1
2
3
4
5
*Main>
----

* using guards
+
[source,haskell]
.loop_counter_using_guards.hs
----
main = do
    let loop i
          | i <= 5 = do
              print i
              loop (i + 1)
          | otherwise = return ()
    loop 1
----
+
[source,haskell]
----
*Main> :load src/prelude/loop_counter_using_guards.hs
[1 of 1] Compiling Main             ( src/prelude/loop_counter_using_guards.hs, interpreted )
Ok, modules loaded: Main.
*Main> main
1
2
3
4
5
*Main>
----

* loop 1 million
+
[source,haskell]
----
import Data.Time.Clock

main = do
    let sum_1million total
          | total < 10^6 = do
              sum_1million (total + 1)
          | otherwise = return total
    t0 <- getCurrentTime
    sum_1million 0 >>= print
    t1 <- getCurrentTime
    print (t1 `diffUTCTime` t0)
----
+
[source,haskell]
----
Prelude> :load src/prelude/loop_1million.hs
[1 of 1] Compiling Main             ( src/prelude/loop_1million.hs, interpreted )
Ok, modules loaded: Main.
*Main> main
1000000
3.0136357s
----
+
[source,console]
.No optimization: compiled with no flags with ghc
----
$ ../../bin/loop_1million
1000000
1.5058498s
----
+
[source,console]
.compiled with `-O2` flags with ghc
----
$ ../../bin/loop_1million
1000000
0.023587s
----
+
[NOTE]
Rust ではデバッグモードで 32ms, リリースビルドで 2µs ぐらい。
+
.References
* https://github.com/nh2/loop[Fast loops for Haskell (for when GHC can't optimize ... - GitHub^]
* https://www.channable.com/tech/how-we-made-haskell-search-strings-as-fast-as-rust[How we made Haskell search strings as fast as Rust^]

==== Loop using range

[source,haskell]
.loop_using_range.hs
----
main = do
    let loop is_true i n
          | is_true == True = do
              print i
              loop ((i + 1) < n) (i + 1) n
          | is_true /= True = return ()
    loop (1 < 6) 1 6
----

[source,haskell]
----
*Main> :load src/prelude/loop_using_range.hs
[1 of 1] Compiling Main             ( src/prelude/loop_using_range.hs, interpreted )
Ok, modules loaded: Main.
*Main> main
1
2
3
4
5
*Main>
----

==== Condition
[source,haskell]
----
Prelude> fact 5 == 120
True
Prelude>
----

==== Recursion

* Implement recursion using recursive calls
+
[source,haskell]
----
Prelude> let fac n = if n == 0 then 1 else n * fac (n-1)
Prelude> fac 42
1405006117752879898543142606244511569936384000000000
Prelude> fac 3
6
Prelude>
----

* Implement recursion using `foldr` in haskell
+
[source,haskell]
----
Prelude> let fac_r n = foldr (*) 1 [1..n]
Prelude> fac_r 42
1405006117752879898543142606244511569936384000000000
Prelude> fac_r 3
6
----

* Implement recursion using `foldr` in haskell
+
[source,haskell]
----
Prelude> let fac_r n = foldr (*) 1 [1..n]
Prelude> fac_r 42
1405006117752879898543142606244511569936384000000000
Prelude> fac_r 3
6
----

* Implement recursion using `foldl` in haskell
+
[source,haskell]
----
Prelude> let fac_l n = foldl (*) 1 [1..n]
Prelude> fac_l 42
1405006117752879898543142606244511569936384000000000
Prelude> fac_l 3
6
----

=== Functions

==== Single results

* using a single parameter
+
[source,haskell]
.A function that calculates the square of an integer
----
Prelude> let square x = x * x
Prelude> square 42
1764
Prelude>
----
+
[source,haskell]
.A function that calculates the factorial of a natural number
----
Prelude> let fact n = product [1..n]
Prelude> fact 5
120
Prelude> fact 10
3628800
Prelude>
----

* using multiple parameters
+
[source,haskell]
.add_2arg_int.hs
----
add :: Integer -> Integer -> Integer
add x y = x + y
main = do
    print(add 42 13)
----

* using strings
+
[source,haskell]
.src/prelude/combine_strings.hs
----
combine_strings :: String -> String -> String
combine_strings s1 s2 = s1 ++ s2
----
+
[source,console]
----
$ ghci src/prelude/combine_strings.hs
----
+
[source,haskell]
.src/prelude/combine_strings.hs
----
*Main> combine_strings "hello" " world"
"hello world"
----

* using tuple
+
[source,haskell]
----
add :: (Integer, Integer) -> Integer
add (x, y) = x + y
main = do
    print(add(42, 13))
----

==== Multiple results

* An example of a use of tuples
+
[source,haskell]
.src/prelude/swap.hs
----
swap :: (String, String) -> (String, String)
swap (a, b) = (b, a)
main = do
    let (a, b) = swap ("hello", "world")
    putStrLn (a ++ " " ++ b)
----
+
[source,console]
----
$ ghci src/prelude/swap.hs
----
+
[source,haskell]
.Results
----
*Main> main
world hello
*Main> swap("hello", "world")
("world","hello")
*Main> swap(swap("hello", "world"))
("hello","world")
*Main> (swap . swap)("hello", "world")
("hello","world")
*Main> swap $ swap("hello", "world")
("hello","world")
----

* Single integer to list of integers 
+
[source,haskell]
.src/prelude/func_int_to_list.hs
----
get_int_list :: Int -> [Int]
get_int_list n = [n] ++ [n]
main = do
    print(get_int_list 3)
----
+
[source,console]
----
$ ghci src/prelude/func_int_to_list.hs
----
+
[source,haskell]
----
*Main> main
[3,3]
*Main> get_int_list 4
[4,4]
----

==== Recursion

* Collatz map
+
[source,haskell]
----
collatz :: Integer -> [Integer]
collatz n | n == 1         = [1]
          | n `mod` 2 == 0 = [n] ++ collatz (n `div` 2)
          | n `mod` 2 == 1 = [n] ++ collatz (n * 3 + 1)
----
+
[source,console]
----
$ ghci src/prelude/collatz.hs
----
+
[source,haskell]
----
*Main> collatz 3
[3,10,5,16,8,4,2,1]
----

==== Higher-order function

* using arguments
+
[source,haskell]
.higher_order_args.hs
----
compute :: (Double -> Double -> Double) -> Double
compute f = f 3 4 ::Double

main = do
    let hypot = \x y -> sqrt (x^2 + y^2)
    print $ hypot 5 12
    print $ compute hypot
    print $ compute (**)
----
+
.Results
----
13.0
5.0
81.0
----

* using tuple and a anonymous function
+
[source,haskell]
.higher_order_tuple.hs
----
compute :: ((Double, Double) -> Double) -> Double
compute (f) = f (3::Double, 4::Double)

main = do
    let hypot = \(x, y) -> sqrt (x^2 + y^2)
    print $ hypot(5, 12)
    print $ compute(hypot)
    print $ compute((\(x, y) -> x**y))
----
+
.Results
----
13.0
5.0
81.0
----

* using tuple and a named function
+
[source,haskell]
----
compute :: ((Double, Double) -> Double) -> Double
compute (f) = f (3::Double, 4::Double)

hypot :: (Double, Double) -> Double
hypot (x, y) = sqrt (x^2 + y^2)

main = do
    print $ hypot(5, 12)
    print $ compute(hypot)
    print $ compute((\(x, y) -> x**y))
----
+
.Results
----
13.0
5.0
81.0
----

===== Map

[source,haskell]
----
Prelude> map (\n -> n + 1) [1,2,3]
[2,3,4]
----

===== Composing functions (合成)

[source,haskell]
----
Prelude> ((+ 1) . (* 2)) 3
7
Prelude> (+ 1) $ (* 2) 3
7
Prelude>
----

=== Monad

[source,haskell]
----
Prelude> Just 1 >>= \x -> return (x*2)
Just 2
Prelude> Nothing >>= \x -> return (x*2)
Nothing
Prelude> [1,2,3] >>= \x -> return (x * 2)
[2,4,6]
Prelude>
----

=== Math

[source,haskell]
.abs
----
*Main> abs (-1)
1
*Main>
----

[source,haskell]
----
*Main> 1254 `div` 1000
1
*Main> 1254 `rem` 1000
254
*Main> 
----

[source,haskell]
.`mod`
----
*Main> (-4) `mod` 3
2
*Main> (-1) `mod` 3
2
*Main>
----

[source,haskell]
.`rem`
----
*Main> (-4) `rem` 3
-1
*Main> (-1) `rem` 3
-1
*Main>
----
