ifndef::leveloffset[]
:toc: left
:toclevels: 3
:icons: font
endif::[]

include::header.adoc[]

== Haskell examples

=== ghci

[source,console]
----
$ ghci
GHCi, version 8.0.2: http://www.haskell.org/ghc/  :? for help
----

[source,console]
----
Prelude> :load src/flow-control/loop_using_range.hs
[1 of 1] Compiling Main             ( src/flow-control/loop_using_range.hs, interpreted )
Ok, one module loaded.
*Main> main
1
2
3
4
5
----

* Import modules
+
[source,haskell]
----
Prelude> :m + Data.List Data.Map Data.Set
----

=== Import

* Import without the `qualified` keyword

** without the `as` keyword
+
[source,haskell]
.Import all functions in a module.
----
import Data.Char

main :: IO ()
main = do
  print $ (Data.Char.chr . Data.Char.ord) 'a'
  print $ (chr . ord) 'a'
----
+
[source,haskell]
.Selectively import just needed functions.
----
import Data.Char (chr, ord)

main :: IO ()
main = do
  print $ (Data.Char.chr . Data.Char.ord) 'a'
  print $ (chr . ord) 'a'
----
+
[source,haskell]
----
*Main> main
'a'
'a'
----

** Using `as` keyword
+
[source,haskell]
.Import all functions in a module.
----
import Data.Char as C

main :: IO ()
main = do
  -- print $ (Data.Char.chr . Data.Char.ord) 'a' -- NG
  print $ (C.chr . C.ord) 'a'
  print $ (chr . ord) 'a'
----
+
[source,haskell]
.Selectively import just needed functions.
----
import Data.Char as C (chr, ord)

main :: IO ()
main = do
  -- print $ (Data.Char.chr . Data.Char.ord) 'a' -- NG
  print $ (C.chr . C.ord) 'a'
  print $ (chr . ord) '
----
+
[source,haskell]
----
*Main> main
'a'
'a'
----

* Qualified import +
A qualified import makes the imported entities available only in qualified form, e.g.

** Without `as` keyword
+
[source,haskell]
----
import qualified Data.Char (chr, ord)

main :: IO ()
main = do
  -- OK
  print $ (Data.Char.chr . Data.Char.ord) 'a'

  -- NG: Variable not in scope: chr :: b0 -> a0
  -- print $ (chr . ord) 'a'
----
+
[source,haskell]
----
*Main> main
'a'
----

** Using `as` keyword
+
[source,haskell]
.Rename the qualified import to something shorter:
----
import qualified Data.Char as C (chr, ord)

main :: IO ()
main = do
  -- NG: No module named ‘Data.Char’ is imported.
  -- print $ (Data.Char.chr . Data.Char.ord) 'a'

  -- OK
  print $ (C.chr . C.ord) 'a'

  -- NG: Variable not in scope: chr :: b0 -> a0
  -- print $ (chr . ord) 'a'
----
+
[source,haskell]
----
*Main> main
'a'
----

=== Type annotations

==== same types

[source,haskell]
----
Prelude> (+) 2 3 ::Double
5.0
----

==== different types

[source,haskell]
----
add_int_and_float :: Integer -> Float -> Float
add_int_and_float x y = fromIntegral(x) + y
main = do
    print(add_int_and_float 1 1.5)
----

.Results
* No type annotations
+
[source,haskell]
----
*Main> add_int_and_float 3 4.5
7.5
----

* NG: Both add type annotations as Integer
+
[source,haskell]
----
*Main> add_int_and_float 3 4.5 :: Integer

<interactive>:3:1: error:
    • Couldn't match expected type ‘Integer’ with actual type ‘Float’
    • In the expression: add_int_and_float 3 4.5 :: Integer
      In an equation for ‘it’: it = add_int_and_float 3 4.5 :: Integer
----

* Add type annotations as Float to right parameter
+
[source,haskell]
----
*Main> add_int_and_float 3 (4.5::Float)
7.5
----

* Add different type annotations to both variables
+
[source,haskell]
----
*Main> add_int_and_float (3::Integer) (4.5::Float)
7.5
----

=== Various types

==== Composite Types

===== Vertex

* No field name
+
[source,haskell]
.src/data-types/composite-types/ex1_no_named_fields/vertex_deriving_show.hs
----
include::../src/data-types/composite-types/ex1_no_named_fields/vertex_deriving_show.hs[]
----
+
[source,console]
----
$ ghci src/data-types/composite-types/ex1_no_named_fields/vertex_deriving_show.hs
GHCi, version 9.4.8: https://www.haskell.org/ghc/  :? for help
[1 of 2] Compiling Main             ( src/data-types/composite-types/ex1_no_named_fields/vertex_deriving_show.hs, interpreted )
Ok, one module loaded.
...snip...
----
+
[source,console]
.ghci src/data-types/composite-types/ex1_no_named_fields/vertex_deriving_show.hs
----
ghci> :show modules
Main             ( src/data-types/composite-types/ex1_no_named_fields/vertex_deriving_show.hs, interpreted )
ghci> :info Vertex
type Vertex :: *
data Vertex = Vertex Int Int
        -- Defined at src/data-types/composite-types/ex1_no_named_fields/vertex_deriving_show.hs:1:1
instance Show Vertex
  -- Defined at src/data-types/composite-types/ex1_no_named_fields/vertex_deriving_show.hs:1:40
ghci> :t Vertex
Vertex :: Int -> Int -> Vertex
ghci> a = Vertex 3 4
ghci> a
Vertex 3 4
ghci> (\(Vertex x _) -> x) a
3
ghci> (\(Main.Vertex x _) -> x) a
3
ghci> (\(Vertex _ y) -> y) a
4
ghci> (\(Vertex x y) -> sqrt(fromIntegral (x*x + y*y))) a
5.0
ghci> main
Vertex 3 4
3
3
4
5.0
Vertex 2 3
----

** Implement show
+
[source,haskell]
.src/data-types/composite-types/ex1_no_named_fields/vertex_impl_show.hs
----
include::../src/data-types/composite-types/ex1_no_named_fields/vertex_impl_show.hs[]
----
+
[source,console]
----
$ ghci src/data-types/composite-types/ex1_no_named_fields/vertex_impl_show.hs
----
+
[source,haskell]
----
*Main> print $ Vertex 3 4
Vertex 3 4
*Main> main
Vertex 3 4
3
3
4
5.0
Vertex 2 3
----

* With filed name
+
[source,haskell]
.src/data-types/composite-types/ex2_named_fields/Euclidean2D.hs
----
include::../src/data-types/composite-types/ex2_named_fields/Euclidean2D.hs[]
----
+
[source,haskell]
.src/data-types/composite-types/ex2_named_fields/Main.hs
----
include::../src/data-types/composite-types/ex2_named_fields/Main.hs[]
----
+
[source,console]
----
$ cd src/data-types/composite-types/ex2_named_fields/
$ ghci Main.hs
----

** Show modules
+
[source,haskell]
----
*Main> :show modules
Euclidean2D      ( Euclidean2D.hs, interpreted )
Main             ( Main.hs, interpreted )
----
+
[source,console]
----
*Main> :info Vertex
data Vertex = Vertex {x :: Int, y :: Int}
        -- Defined at Euclidean2D.hs:2:1
instance [safe] Show Vertex -- Defined at Euclidean2D.hs:3:10
*Main> :t Vertex
Vertex :: Int -> Int -> Vertex
*Main> :t x
x :: Vertex -> Int
*Main> :info x
data Vertex = Vertex {x :: Int, ...}
        -- Defined at Euclidean2D.hs:2:24
*Main> :t y
y :: Vertex -> Int
*Main> :info y
data Vertex = Vertex {..., y :: Int}
        -- Defined at Euclidean2D.hs:2:34
----

** Use Vertex
+
[source,haskell]
----
*Main> a = Vertex { x = 3, y = 4 }
*Main> a
Vertex {x=3,y=4}
*Main> x a
3
*Main> Euclidean2D.x a
3
*Main> (\v -> sqrt ( fromIntegral (x v * x v + y v * y v) )) a
5.0
*Main> (\v -> sqrt ( fromIntegral (x v * x v + y v * y v) )) (Vertex 5 12)
13.0
----

** Run main
+
[source,haskell]
----
*Main> main
Vertex {x=3,y=4}
3
3
4
5.0
----

==== Enum

* Enum to Int
+
[source,haskell]
.src/classes/enum_to_int.hs
----
include::../src/classes/enum_to_int.hs[]
----
+
[source,console]
----
$ ghci src/classes/enum_to_int.hs
----
+
[source,haskell]
----
*Main> main
0
1
2
[0,1,2]
----

* Int to enum
+
[source,haskell]
.src/classes/int_to_enum.hs
----
include::../src/classes/int_to_enum.hs[]
----
+
[source,console]
----
$ ghci src/classes/int_to_enum.hs
----
+
[source,haskell]
----
*Main> main
Apple
Orange
Kiwi
[Apple,Orange,Kiwi]
*Main> :t (map toEnum [0, 1, 2] :: [Fruits])
(map toEnum [0, 1, 2] :: [Fruits]) :: [Fruits]
----

===== Matching enum

* Using pattern matching
+
[source,haskell]
.src/classes/enum_pattern_matching.hs
----
include::../src/classes/enum_pattern_matching.hs[]
----
+
[source,console]
----
$ ghci src/classes/enum_pattern_matching.hs
----
+
[source,haskell]
----
*Main> main
Apple: I like apples.
Orange: I like oranges.
Kiwi: I like kiwis.
----

* Using case expressions
+
[source,haskell]
.src/classes/enum_case_of.hs
----
include::../src/classes/enum_case_of.hs[]
----
+
[source,console]
----
$ ghci src/classes/enum_case_of.hs
----
+
[source,haskell]
----
*Main> main
Apple: I like apples.
Orange: I like oranges.
Kiwi: I like kiwis.
----

* Using where bindings
+
[source,haskell]
.src/classes/enum_where_binding.hs
----
include::../src/classes/enum_where_binding.hs[]
----
+
[source,console]
----
$ ghci src/classes/enum_where_binding.hs
----
+
[source,haskell]
----
*Main> main
Apple: I like apples.
Orange: I like oranges.
Kiwi: I like kiwis.
----

==== Tuples

* fst and snd
+
[source,haskell]
----
Prelude> fst(1, 2)
1
Prelude> snd(1, 2)
2
----

* swap
+
[source,haskell]
----
Prelude> import Data.Tuple
Prelude Data.Tuple> swap("hello", "world")
("world","hello")
Prelude Data.Tuple> swap $ swap("hello", "world")
("hello","world")
Prelude Data.Tuple> (swap . swap)("hello", "world")
("hello","world")
----

[source,haskell]
----
Prelude> curry fst "hello" "world"
"hello"
Prelude> uncurry div (10, 5)
2
Prelude>
----

=== Flow control statements

==== Loop using counter

* not using using guards
+
[source,haskell]
.loop_counter_no_guards.hs
----
include::../src/flow-control/loop_counter_no_guards.hs[]
----
+
[source,shell]
----
ghci -Wall src/flow-control/loop_counter_no_guards.hs
----
+
[source,haskell]
----
*Main> main
1
2
3
4
5
----

* using guards
+
[source,haskell]
.loop_counter_using_guards.hs
----
include::../src/flow-control/loop_counter_using_guards.hs[]
----
+
[source,shell]
----
ghci -Wall src/flow-control/loop_counter_using_guards.hs
----
+
[source,haskell]
----
*Main> main
1
2
3
4
5
----

* loop 1 million
+
[source,haskell]
----
import Data.Time.Clock

main = do
    let sum_1million total
          | total < 10^6 = do
              sum_1million (total + 1)
          | otherwise = return total
    t0 <- getCurrentTime
    sum_1million 0 >>= print
    t1 <- getCurrentTime
    print (t1 `diffUTCTime` t0)
----
+
[source,haskell]
----
Prelude> :load src/ghci/loop_1million.hs
[1 of 1] Compiling Main             ( src/ghci/loop_1million.hs, interpreted )
Ok, modules loaded: Main.
*Main> main
1000000
3.0136357s
----
+
[source,console]
.No optimization: compiled with no flags with ghc
----
$ ../../bin/loop_1million
1000000
1.5058498s
----
+
[source,console]
.compiled with `-O2` flags with ghc
----
$ ../../bin/loop_1million
1000000
0.023587s
----
+
[NOTE]
Rust ではデバッグモードで 32ms, リリースビルドで 2µs ぐらい。
+
.References
* https://github.com/nh2/loop[Fast loops for Haskell (for when GHC can't optimize ... - GitHub^]
* https://www.channable.com/tech/how-we-made-haskell-search-strings-as-fast-as-rust[How we made Haskell search strings as fast as Rust^]

==== Loop using range

[source,haskell]
.loop_using_range.hs
----
include::../src/flow-control/loop_using_range.hs[]
----

[source,shell]
----
ghci -Wall src/flow-control/loop_using_range.hs
----

[source,haskell]
----
*Main> :load src/flow-control/loop_using_range.hs
[1 of 1] Compiling Main             ( src/flow-control/loop_using_range.hs, interpreted )
Ok, modules loaded: Main.
*Main> main
1
2
3
4
5
*Main>
----

==== Recursion

===== Reverse

[source,haskell]
.src/recursion/reverse.hs
----
include::../src/recursion/reverse.hs[]
----

[source,haskell]
.Results
----
*Main> reverse' "abc"
"cba"
----

===== Quicksort

[source,haskell]
.src/recursion/quicksort.hs
----
include::../src/recursion/quicksort.hs[]
----

[source,haskell]
.Results
----
*Main> quicksort [6, 1, 1, 8, 6, 5, 3, 7, 2, 1, 4, 3, 8, 9]
[1,1,1,2,3,3,4,5,6,6,7,8,8,9]
*Main> quicksort "I have a pen."
"   .Iaaeehnpv"
*Main> quicksort ["Orange", "Apple", "Kiwi", "Banana", "Peach", "Watermelon"]
["Apple","Banana","Kiwi","Orange","Peach","Watermelon"]
----

===== Factorial

* Implement recursion using recursive calls
+
[source,haskell]
.src/math/fac.hs
----
include::../src/math/fac.hs[]
----
+
[source,haskell]
----
*Main> :set +s
*Main> fac_p 42
1405006117752879898543142606244511569936384000000000
(0.02 secs, 129,936 bytes)
*Main> fac_g 42
1405006117752879898543142606244511569936384000000000
(0.02 secs, 132,320 bytes)
*Main> fac_if_then_else 42
1405006117752879898543142606244511569936384000000000
(0.02 secs, 132,312 bytes)
----

* Implement recursion using `foldr` in haskell
+
[source,haskell]
----
Prelude> let fac_r n = foldr (*) 1 [1..n]
Prelude> fac_r 42
1405006117752879898543142606244511569936384000000000
Prelude> fac_r 3
6
----

* Implement recursion using `foldl` in haskell
+
[source,haskell]
----
Prelude> let fac_l n = foldl (*) 1 [1..n]
Prelude> fac_l 42
1405006117752879898543142606244511569936384000000000
Prelude> fac_l 3
6
----

===== Fibonacci sequence

[source,haskell]
.src/math/fib.hs
----
include::../src/math/fib.hs[]
----

===== Collatz map

* Collatz map
+
[source,haskell]
.src/math/collatz_with_guards.hs
----
include::../src/math/collatz_with_guards.hs[]
----
+
[source,haskell]
.src/math/collatz_with_pattern.hs
----
include::../src/math/collatz_with_pattern.hs[]
----

** Run
+
[source,console]
----
$ ghci src/math/collatz_with_guards.hs
----
+
[source,haskell]
----
*Main> collatz 3
[3,10,5,16,8,4,2,1]
----

=== Functions

==== using a single parameter

* Using integers
+
[source,haskell]
.A function that calculates the square of an integer
----
Prelude> let square x = x * x
Prelude> square 42
1764
Prelude>
----

* Using Floating type class +
Floating is a type class.
+
[source,haskell]
----
Prelude> pi :: Float
3.1415927
Prelude> pi :: Double
3.141592653589793
----
+
[source,haskell]
.src/functions/circle_area.hs
----
include::../src/functions/circle_area.hs[]
----
+
[source,console]
.Run ghci
----
$ ghci src/functions/circle_area.hs
----
+
[source,haskell]
.Results
----
*Main> :t circle_area_float
circle_area_float :: Float -> Float
*Main> circle_area_float 1
3.1415927
*Main> :t circle_area_double
circle_area_double :: Double -> Double
*Main> circle_area_double 1
3.141592653589793
*Main> circle_area_floating 1 :: Float
3.1415927
*Main> circle_area_floating 1 :: Double
3.141592653589793
----

* Using Real, etc
+
[source,haskell]
.src/math/squared.hs
----
include::../src/math/squared.hs[]
----

** Integer
+
[source,haskell]
.3037000499^2
----
*Main> sqInt 3037000499
9223372030926249001
*Main> sqInteger 3037000499
9223372030926249001
*Main> sqIntegral 3037000499::Int
9223372030926249001
----
+
[source,haskell]
.3037000500^2 - Int
----
*Main> sqInt 3037000500
-9223372036709301616
*Main> sqIntegral 3037000500::Int
-9223372036709301616
----
+
[source,haskell]
.3037000500^2 - Integer
----
*Main> sqInteger  3037000500
9223372037000250000
*Main> sqIntegral 3037000500::Integer
9223372037000250000
----

** Floating
+
[source,haskell]
.sqrt(2) - Float
----
*Main> sqFloat (sqrt(2)::Float)
1.9999999
*Main> sqFloating (sqrt(2)::Float)
1.9999999
*Main> sqFractional (sqrt(2)::Float)
1.9999999
*Main> sqReal (sqrt(2)::Float)
1.9999999
*Main> sqRealFrac (sqrt(2)::Float)
1.9999999
*Main> sqRealFloat (sqrt(2)::Float)
1.9999999
*Main> sqNum (sqrt(2)::Float)
1.9999999
*Main> sqComplex ((sqrt(2)::Float) :+ 0)
1.9999999 :+ 0.0
----
+
[source,haskell]
.sqrt(2) - Double
----
*Main> sqDouble (sqrt(2)::Double)
2.0000000000000004
*Main> sqFloating (sqrt(2)::Double)
2.0000000000000004
*Main> sqFractional (sqrt(2)::Double)
2.0000000000000004
*Main> sqReal (sqrt(2)::Double)
2.0000000000000004
*Main> sqRealFrac (sqrt(2)::Double)
2.0000000000000004
*Main> sqRealFloat (sqrt(2)::Double)
2.0000000000000004
*Main> sqNum (sqrt(2)::Double)
2.0000000000000004
*Main> sqComplex ((sqrt(2)::Double) :+ 0)
2.0000000000000004 :+ 0.0
----

** Rational
+
[source,haskell]
.Rational
----
*Main> sqFractional (1/3 :: Rational)
1 % 9
*Main> sqRealFrac (1/3 :: Rational)
1 % 9
*Main> sqReal (1/3 :: Rational)
1 % 9
*Main> sqNum (1/3 :: Rational)
1 % 9
----

** Complex numbers
+
[source,haskell]
.Complex numbers
----
*Main> sqComplex (0 :+ 1)
(-1.0) :+ 0.0
*Main> sqFractional (0 :+ 1)
(-1.0) :+ 0.0
*Main> sqNum (0 :+ 1)
(-1.0) :+ 0.0
----

==== Multiple parameters

* Using Int
+
[source,haskell]
.add_2arg_int.hs
----
include::../src/functions/add_2arg_int.hs[]
----
+
[source,haskell]
----
*Main> add 42 13
55
*Main> add 42.0 13.0

<interactive>:3:5: error:
    • No instance for (Fractional Int) arising from the literal ‘42.0’
    • In the first argument of ‘add’, namely ‘42.0’
      In the expression: add 42.0 13.0
      In an equation for ‘it’: it = add 42.0 13.0
*Main> add (maxBound :: Int) 0
9223372036854775807
*Main> add (maxBound :: Int) 1
-9223372036854775808
*Main> add (minBound :: Int) (0)
-9223372036854775808
*Main> add (minBound :: Int) (-1)
9223372036854775807
----

* Using Num
+
[source,haskell]
.add_2arg_num.hs
----
include::../src/functions/add_2arg_num.hs[]
----

** Add variable types
+
[source,haskell]
----
*Main> add (42 :: Int) 13
55
*Main> add (42 :: Integer) 13
55
*Main> add (1/3) (1/2) :: Rational
5 % 6
*Main> add 42.0 13.0
55.0
*Main> add (42 :: Float) 13
55.0
*Main> add (42 :: Double) 13
55.0
----

** Overflow & underflow
+
[source,haskell]
.NG: Int
----
*Main> add (maxBound :: Int) 1
-922337203685477580
*Main> add (minBound :: Int) (-1)
9223372036854775807
----
+
[source,haskell]
.OK: Integer
----
*Main> add (toInteger (maxBound :: Int)) 1
9223372036854775808
*Main> add (toInteger (minBound :: Int)) (-1)
-9223372036854775809
----

* using strings
+
[source,haskell]
.src/data-types/string/combine_strings.hs
----
include::../src/data-types/string/combine_strings.hs[]
----
+
[source,console]
----
$ ghci src/data-types/string/combine_strings.hs
----
+
[source,haskell]
.src/data-types/string/combine_strings.hs
----
*Main> combine_strings "hello" " world"
"hello world"
----

* using tuple
+
[source,haskell]
.src/functions/add_2arg_tuple.hs
----
include::../src/functions/add_2arg_tuple.hs[]
----

* using list

** XOR
+
[source,haskell]
.src/functions/xor.hs
----
include::../src/functions/xor.hs[]
----
+
[source,haskell]
----
*Main> xor [] :: [Int]
DEBUG[] =>
[]
*Main> xor [1] :: [Int]
DEBUG[1]
[1]
*Main> xor [1, 1] :: [Int]
DEBUG[1,1]
[0]
*Main> xor [1, 1, 1] :: [Int]
DEBUG(1:1:[1])
DEBUG[1,1]
DEBUG[0,1]
[1]
*Main> xor [1, 1, 1, 1] :: [Int]
DEBUG(1:1:[1,1])
DEBUG[1,1]
DEBUG(0:1:[1])
DEBUG[0,1]
DEBUG[1,1]
[0]
----

** Remove the second element
+
[source,haskell]
.src/functions/remove_2nd_element.hs
----
include::../src/functions/remove_2nd_element.hs[]
----
+
[source,haskell]
.Results
----
*Main> remove2ndElement ([] :: [Int])
[]
*Main> remove2ndElement [1]
[1]
*Main> remove2ndElement [1, 2]
[1]
*Main> remove2ndElement [1, 2, 3]
[1,3]
*Main> remove2ndElement [1, 2, 3, 4]
[1,3,4]
----

==== Multiple results

* An example of a use of tuples
+
[source,haskell]
.src/functions/swap_two_tuple.hs
----
include::../src/functions/swap_two_tuple.hs[]
----
+
[source,console]
----
$ ghci src/functions/swap_two_tuple.hs
----
+
[source,haskell]
.Results
----
*Main> swap("hello", "world")
("world","hello")
*Main> swap(swap("hello", "world"))
("hello","world")
*Main> (swap . swap)("hello", "world")
("hello","world")
*Main> swap $ swap("hello", "world")
("hello","world")
*Main> swap (1 :: Int, 2) == (2, 1)
True
----

* Single integer to list of integers 
+
[source,haskell]
.src/functions/func_int_to_list.hs
----
include::../src/functions/func_int_to_list.hs[]
----
+
[source,console]
----
$ ghci src/functions/func_int_to_list.hs
----
+
[source,haskell]
----
*Main> main
[3,3]
*Main> get_int_list 4
[4,4]
----

* Various types
+
[source,haskell]
----
include::../src/functions/make_tuple_various_types.hs[]
----
+
[source,console]
----
$ ghci src/functions/make_tuple_various_types.hs
----
+
[source,haskell]
.Results
----
*Main> main
(3,1 % 3,3.14,"hello")
(3,1 % 3,3.14,"world")
----

==== Order

[source,haskell]
.src/functions/max_num.hs
----
include::../src/functions/max_num.hs[]
----

.Results
* max_num
+
[source,haskell]
----
*Main> max_num (3 :: Int) 4
4
*Main> max_num (pi::Float) (sqrt(2)::Float)
3.1415927
*Main> max_num (pi::Double) (sqrt(2)::Double)
3.141592653589793
*Main> max_num (1/3 ::Rational) 1/2
1 % 2
----

* max_gen
+
[source,haskell]
----
*Main> max_gen (3 :: Int) 4
4
*Main> max_gen (pi::Float) (sqrt(2)::Float)
3.1415927
*Main> max_gen (pi::Double) (sqrt(2)::Double)
3.141592653589793
*Main> max_gen (1/3 ::Rational) 1/2
1 % 2
*Main> max_gen True False
True
*Main> max_gen 'z' 'a'
'z'
*Main> max_gen "apple" "kiwi"
"kiwi"
----

==== Eq

[source,haskell]
.src/functions/eq.hs
----
include::../src/functions/eq.hs[]
----

[source,haskell]
----
*Main> eq (3 :: Int) 3
True
*Main> eq (1/3 :: Rational) (1/3 :: Rational)
True
*Main> eq (pi::Float) 3.1415927
True
*Main> eq (pi::Double) 3.141592653589793
True
*Main> eq False False
True
*Main> eq 'a' 'a'
True
*Main> eq "hello" "hello"
True
*Main> eq (1, 2) (1, 2)
True
----

==== Higher-order function

* using arguments
+
[source,haskell]
.higher_order_args.hs
----
include::../src/functions/higher_order_args.hs[]
----
+
.Results
----
13.0
5.0
81.0
----

* using tuple and a anonymous function
+
[source,haskell]
.higher_order_tuple.hs
----
include::../src/functions/higher_order_tuple.hs[]
----
+
.Results
----
13.0
5.0
81.0
----

* using tuple and a named function
+
[source,haskell]
----
compute :: ((Double, Double) -> Double) -> Double
compute (f) = f (3::Double, 4::Double)

hypot :: (Double, Double) -> Double
hypot (x, y) = sqrt (x^2 + y^2)

main = do
    print $ hypot(5, 12)
    print $ compute(hypot)
    print $ compute((\(x, y) -> x**y))
----
+
.Results
----
13.0
5.0
81.0
----

===== Map

[source,haskell]
----
Prelude> map (\n -> n + 1) [1,2,3]
[2,3,4]
----

===== Composing functions (合成)

[source,haskell]
----
Prelude> ((+ 1) . (* 2)) 3
7
Prelude> (+ 1) $ (* 2) 3
7
Prelude>
----
