ifndef::leveloffset[]
:toc: left
:toclevels: 3
:icons: font
endif::[]

include::header.adoc[]

== Haskell examples

=== ghci

[source,console]
----
$ ghci
GHCi, version 8.0.2: http://www.haskell.org/ghc/  :? for help
----

=== Type annotations

==== same types

[source,haskell]
----
Prelude> (+) 2 3 ::Double
5.0
----

==== different types

[source,haskell]
----
add_int_and_float :: Integer -> Float -> Float
add_int_and_float x y = fromIntegral(x) + y
main = do
    print(add_int_and_float 1 1.5)
----

.Results
* No type annotations
+
[source,haskell]
----
*Main> add_int_and_float 3 4.5
7.5
----

* NG: Both add type annotations as Integer
+
[source,haskell]
----
*Main> add_int_and_float 3 4.5 :: Integer

<interactive>:3:1: error:
    • Couldn't match expected type ‘Integer’ with actual type ‘Float’
    • In the expression: add_int_and_float 3 4.5 :: Integer
      In an equation for ‘it’: it = add_int_and_float 3 4.5 :: Integer
----

* Add type annotations as Float to right parameter
+
[source,haskell]
----
*Main> add_int_and_float 3 (4.5::Float)
7.5
----

* Add different type annotations to both variables
+
[source,haskell]
----
*Main> add_int_and_float (3::Integer) (4.5::Float)
7.5
----

==== String

===== Concatenate vector of chars into single string


* Chars
+
[source,haskell]
----
Prelude> ['a', 'b', 'c']
"abc"
----

* Using the colon(`:`) operator to prepend chars
+
[source,haskell]
----
Prelude> 'a':'b':'c':[]
"abc"
----

===== Concatenate vector of strings into single string

* Using `(++)`
+
[source,haskell]
----
Prelude> :t (++)
(++) :: [a] -> [a] -> [a]
Prelude> "abc" ++ "123" ++ "cdf"
"abc123cdf"
Prelude>
----

* Using `concat`
+
[source,haskell]
----
Prelude> :t concat
concat :: Foldable t => t [a] -> [a]
Prelude> concat ["abc", "123", "cdf"]
"abc123cdf"
Prelude>
----

* Using `Control.Monad.join`
+
[source,haskell]
----
Prelude> Control.Monad.join ["abc", "123", "cdf"]
"abc123cdf"
----
+
[source,haskell]
----
Prelude> import Control.Monad
Prelude Control.Monad> join ["abc", "123", "cdf"]
"abc123cdf"
Prelude Control.Monad>
----

* You can also use the list monad to reduce the list to a single string, then re-wrap the result in a list.
+
[source,haskell]
----
Prelude> ["abc", "123", "cdf"] >>= id
"abc123cdf"
Prelude>
----

* using `foldr` and `foldl`
+
[source,haskell]
----
Prelude> foldr (\s_prepend s -> s_prepend ++ s) "" ["abc", "123", "cdf"]
"abc123cdf"
Prelude> foldl (\s s_add -> s ++ s_add) "" ["abc", "123", "cdf"]
"abc123cdf"
----

===== Join strings with a delimiter

* Using `Data.List.intercalate`
+
[source,haskell]
----
Prelude> Data.List.intercalate ", " ["John", "Due"]
"John, Due"
----
+
[source,haskell]
----
Prelude> import Data.List
Prelude Data.List> intercalate ", " ["John", "Due"]
"John, Due"
Prelude Data.List>
----

==== Composite Types

===== Vertex

* No field name
+
[source,haskell]
----
Prelude> data Vertex = Vertex Int Int deriving (Show)
Prelude> :t Vertex
Vertex :: Int -> Int -> Vertex
Prelude> let a = Vertex 3 4
Prelude> a
Vertex 3 4
Prelude> (\(Vertex x _) -> x) a
3
Prelude> (\(Vertex _ y) -> y) a
4
Prelude> (\(Vertex x y) -> sqrt(fromIntegral (x*x + y*y))) a
5.0
----

** Implement show
+
[source,haskell]
.src/ghci/composite-types/vertex_impl_show.hs
----
data Vertex = Vertex Int Int
instance Show Vertex where
  show (Vertex x y) = "Vertex (" ++ show x ++ "," ++ show y ++ ")"

main = do
  let a = Vertex 1 2
      b = Vertex 2 3
  print a
  print b
----
+
[source,console]
----
$ ghci src/ghci/composite-types/vertex_deriving_show.hs
----
+
[source,haskell]
----
*Main> main
Vertex (1,2)
Vertex (2,3)
----

* With filed name
+
[source,haskell]
----
Prelude> data Vertex = Vertex { x :: Int, y :: Int } deriving (Show)
Prelude> :t Vertex
Vertex :: Int -> Int -> Vertex
Prelude> :t x
x :: Vertex -> Int
Prelude> :t y
y :: Vertex -> Int
Prelude> a = Vertex { x = 3, y = 4 }
Prelude> a
Vertex {x = 3, y = 4}
Prelude> x a
3
Prelude> y a
4
Prelude> (\v -> sqrt ( fromIntegral (x v * x v + y v * y v) )) a
5.0
----

==== List

* Make a list
+
[source,haskell]
----
Prelude> [1, 2, 3]
[1,2,3]
Prelude> :t []
[] :: [t]
----
+
[source,haskell]
.Using the colon operator
----
Prelude> 1:2:3:[]
[1,2,3]
Prelude> :t (:)
(:) :: a -> [a] -> [a]
----

* Prepend the item to the list
+
.Using the colon operator. colon is the "prepend" operator
[source,haskell]
----
Prelude> 1:2:3:[]
[1,2,3]
Prelude> "apple":"banana":"cherry":["durian"]
["apple","banana","cherry","durian"]
----
+
[source,haskell]
----
Prelude> (:) 1 []
[1]
Prelude> (:) 1 ((:) 2 ((:) 3 []))
[1,2,3]
Prelude> (:) 1 $ (:) 2 $ (:) 3 []
[1,2,3]
Prelude> ((:) 1 . (:) 2 . (:) 3) []
[1,2,3]
----

* Returns the first item of a list
+
[source,haskell]
.Using `head`
----
Prelude> head []
*** Exception: Prelude.head: empty list
Prelude> head [1, 2, 3]
1
Prelude> head [1..]
1
----
+
[source,haskell]
----
Prelude> let head' (h:_) = h
Prelude> :t head'
head' :: [t] -> t
Prelude> head' []
*** Exception: <interactive>:61:5-19: Non-exhaustive patterns in function head'

Prelude> head' [1, 2, 3]
1
Prelude> head' [1..]
1
Prelude> head' ["apple", "banana", "cherry", "durian"]
"apple"
----
+
[source,haskell]
.Using `take`
----
Prelude> take 1 []
[]
Prelude> take 1 [1, 2, 3]
[1]
Prelude> take 3 [1..]
[1,2,3]
----
+
[source,haskell]
.Using `foldr`
----
Prelude> foldr (\x _ -> [x]) [] []
[]
Prelude> foldr (\x _ -> [x]) [] [1, 2, 3]
[1]
Prelude> foldr (\x _ -> [x]) [] [1..]
[1]
Prelude> foldr (\s _ -> [s]) [] []
[]
Prelude> foldr (\s _ -> [s]) [] ["apple", "banana", "cherry", "durian"]
["apple"]
----

* returns the last item of a list
+
[source,haskell]
.Using `last`
----
Prelude> last [1, 2, 3]
3
----
+
[source,haskell]
.Using `foldl`
----
Prelude> foldl (\_ x -> x) 0 [1, 2, 3]
3
----

* it accepts a list and returns the list without its last item
+
[source,haskell]
----
Prelude> init [1, 2, 3]
[1,2]
----

* it accepts a list and returns the list without its first item
+
[source,haskell]
----
Prelude> tail ["A", "B", "C"]
["B","C"]
Prelude> drop 1 ["A", "B", "C"]
["B","C"]
----
+
[source,haskell]
----
Prelude> let tail' (_:t) = t
Prelude> :t tail'
tail' :: [t] -> [t]
Prelude> tail' []
*** Exception: <interactive>:67:5-19: Non-exhaustive patterns in function tail'

Prelude> tail' ["A", "B", "C"]
["B","C"]
----

* The length of a list
+
[source,haskell]
----
Prelude> :t length
length :: Foldable t => t a -> Int
Prelude> length ["apple", "banana", "cherry", "durian"]
4
----
+
[source,haskell]
.The length of a list without the "length" function in Haskell
----
Prelude> foldr (\_ n -> n + 1) 0 ["apple", "banana", "cherry", "durian"]
4
----

* Reverse a list in haskell
+
[source,haskell]
----
Prelude> reverse ["apple","banana","cherry"]
["cherry","banana","apple"]
----
+
[source,haskell]
----
Prelude> foldr (\x xs -> xs ++ [x]) [] ["apple", "banana", "cherry"]
["cherry","banana","apple"]
----

* Combine two lists
+
[source,haskell]
----
Prelude> [1, 2, 3] ++ [4, 5, 6]
[1,2,3,4,5,6]
----


* Program to left rotate a list
+
[source,haskell]
----
Prelude> let rotate_l a = tail a ++ take 1 a
Prelude> :t rotate_l
rotate_l :: [a] -> [a]
Prelude> rotate_l [1, 2, 3]
[2,3,1]
Prelude> rotate_l $ rotate_l [1, 2, 3]
[3,1,2]
Prelude> rotate_l $ rotate_l $ rotate_l [1, 2, 3]
[1,2,3]
----

* Program to right rotate a list
+
[source,haskell]
----
Prelude> let rotate_r a = [last a] ++ init a
Prelude> :t rotate_r
rotate_r :: [a] -> [a]
Prelude> rotate_r [1, 2, 3]
[3,1,2]
Prelude> rotate_r $ rotate_r [1, 2, 3]
[2,3,1]
Prelude> rotate_r $ rotate_r $ rotate_r [1, 2, 3]
[1,2,3]
Prelude> rotate_l $ rotate_r [1, 2, 3]
[1,2,3]
----

===== List comprehension (リストの内包表記)

* Filter multiples of 3 from a List
+
[source,haskell]
----
Prelude> [p | p <- [1..10], p `mod` 3 == 0]
[3,6,9]
Prelude> filter (\x -> x `mod` 3 == 0) [1..10]
[3,6,9]
Prelude> [1..10] >>= \x -> if x `mod` 3 == 0 then pure x else []
[3,6,9]
Prelude> [1..10] >>= \x -> if x `mod` 3 == 0 then x:[] else []
[3,6,9]
Prelude> [1..10] >>= \x -> if x `mod` 3 == 0 then [x] else []
[3,6,9]
----
+
[source,haskell]
.Using infinite lists
----
Prelude> take 3 [p | p <- [1..], p `mod` 3 == 0]
[3,6,9]
Prelude> take 3 $ filter (\x -> x `mod` 3 == 0) [1..]
[3,6,9]
Prelude> take 3 $ [1..] >>= \x -> if x `mod` 3 == 0 then pure x else []
[3,6,9]
----

* Making a list of divisors in Haskell
+
[source,haskell]
----
Prelude> [x | x <- [2..9], 10 `mod` x == 0]
[2,5]
Prelude> filter (\x -> 10 `mod` x == 0) [2..9]
[2,5]
Prelude> [2..9] >>= \x -> if 10 `mod` x == 0 then pure x else []
[2,5]
----

* Find cubic root of a number
+
[source,haskell]
----
Prelude> [x | x <- [2..7], x * x * x == 8]
[2]
Prelude> filter (\x -> x * x * x == 8) [2..7]
[2]
Prelude> [2..7] >>= \x -> if x * x * x == 8 then pure x else []
[2]
----
+
[source,haskell]
.Using infinite lists
----
Prelude> take 1 $ [x | x <- [2..], x * x * x == 8]
[2]
Prelude> take 1 $ filter (\x -> x * x * x == 8) [2..]
[2]
Prelude> take 1 $ [2..] >>= \x -> if x * x * x == 8 then pure x else []
[2]
----

* Combining two lists
+
[source,haskell]
----
Prelude> [(x,y) | x <- [1,2], y <- [1,2,3]]
[(1,1),(1,2),(1,3),(2,1),(2,2),(2,3)]
----

===== Infinite lists

* Make infinite lists
+
[source,haskell]
----
Prelude> a = 1:a
Prelude> take 3 a
[1,1,1]
Prelude> take 10 [2,4..]
[2,4,6,8,10,12,14,16,18,20]
----
+
[source,haskell]
----
Prelude> take 6 ([2, 3] ++ a)
[2,3,1,1,1,1]
----
+
[source,haskell]
----
Prelude> c = 1:[x * 2 | x <- c]
Prelude> take 10 c
[1,2,4,8,16,32,64,128,256,512]
----

* Gets the first one element from the infinite list.
+
[source,haskell]
----
Prelude> head [1..]
1
----

* Takeing the first three elements from the infinite list.
+
[source,haskell]
----
Prelude> take 3 [1..]
[1,2,3]
----

* Determine if there is an element that meets the conditions in the infinite list.
+
[source,haskell]
----
Prelude> :set +s
Prelude> null [x | x <- [1..], x == 1]
False
(0.00 secs, 64,016 bytes)
Prelude> null [x | x <- [1..], x == 100000]
False
(0.05 secs, 8,865,312 bytes)
----

* Add one
+
[source,haskell]
----
Prelude> take 10 $ map (+ 1) [1..]
[2,3,4,5,6,7,8,9,10,11]
Prelude> take 10 [ x + 1 | x <- [1..] ]
[2,3,4,5,6,7,8,9,10,11]
----


==== Tuples

* fst and snd
+
[source,haskell]
----
Prelude> fst(1, 2)
1
Prelude> snd(1, 2)
2
----

* swap
+
[source,haskell]
----
Prelude> import Data.Tuple
Prelude Data.Tuple> swap("hello", "world")
("world","hello")
Prelude Data.Tuple> swap $ swap("hello", "world")
("hello","world")
Prelude Data.Tuple> (swap . swap)("hello", "world")
("hello","world")
----

[source,haskell]
----
Prelude> curry fst "hello" "world"
"hello"
Prelude> uncurry div (10, 5)
2
Prelude>
----

=== Flow control statements

==== Loop using counter

* not using using guards
+
[source,haskell]
.loop_counter_no_guards.hs
----
main = do
    let loop 6 = return ()
        loop i = do
            print i
            loop (i + 1)
    loop 1
----
+
[source,haskell]
----
*Main> :load src/ghci/loop_counter_no_guards.hs
[1 of 1] Compiling Main             ( src/ghci/loop_counter_no_guards.hs, interpreted )
Ok, modules loaded: Main.
*Main> main
1
2
3
4
5
*Main>
----

* using guards
+
[source,haskell]
.loop_counter_using_guards.hs
----
main = do
    let loop i
          | i <= 5 = do
              print i
              loop (i + 1)
          | otherwise = return ()
    loop 1
----
+
[source,haskell]
----
*Main> :load src/ghci/loop_counter_using_guards.hs
[1 of 1] Compiling Main             ( src/ghci/loop_counter_using_guards.hs, interpreted )
Ok, modules loaded: Main.
*Main> main
1
2
3
4
5
*Main>
----

* loop 1 million
+
[source,haskell]
----
import Data.Time.Clock

main = do
    let sum_1million total
          | total < 10^6 = do
              sum_1million (total + 1)
          | otherwise = return total
    t0 <- getCurrentTime
    sum_1million 0 >>= print
    t1 <- getCurrentTime
    print (t1 `diffUTCTime` t0)
----
+
[source,haskell]
----
Prelude> :load src/ghci/loop_1million.hs
[1 of 1] Compiling Main             ( src/ghci/loop_1million.hs, interpreted )
Ok, modules loaded: Main.
*Main> main
1000000
3.0136357s
----
+
[source,console]
.No optimization: compiled with no flags with ghc
----
$ ../../bin/loop_1million
1000000
1.5058498s
----
+
[source,console]
.compiled with `-O2` flags with ghc
----
$ ../../bin/loop_1million
1000000
0.023587s
----
+
[NOTE]
Rust ではデバッグモードで 32ms, リリースビルドで 2µs ぐらい。
+
.References
* https://github.com/nh2/loop[Fast loops for Haskell (for when GHC can't optimize ... - GitHub^]
* https://www.channable.com/tech/how-we-made-haskell-search-strings-as-fast-as-rust[How we made Haskell search strings as fast as Rust^]

==== Loop using range

[source,haskell]
.loop_using_range.hs
----
main = do
    let loop is_true i n
          | is_true == True = do
              print i
              loop ((i + 1) < n) (i + 1) n
          | is_true /= True = return ()
    loop (1 < 6) 1 6
----

[source,haskell]
----
*Main> :load src/ghci/loop_using_range.hs
[1 of 1] Compiling Main             ( src/ghci/loop_using_range.hs, interpreted )
Ok, modules loaded: Main.
*Main> main
1
2
3
4
5
*Main>
----

==== Condition
[source,haskell]
----
Prelude> fact 5 == 120
True
Prelude>
----

==== Recursion

* Implement recursion using recursive calls
+
[source,haskell]
----
Prelude> let fac n = if n == 0 then 1 else n * fac (n-1)
Prelude> fac 42
1405006117752879898543142606244511569936384000000000
Prelude> fac 3
6
Prelude>
----

* Implement recursion using `foldr` in haskell
+
[source,haskell]
----
Prelude> let fac_r n = foldr (*) 1 [1..n]
Prelude> fac_r 42
1405006117752879898543142606244511569936384000000000
Prelude> fac_r 3
6
----

* Implement recursion using `foldl` in haskell
+
[source,haskell]
----
Prelude> let fac_l n = foldl (*) 1 [1..n]
Prelude> fac_l 42
1405006117752879898543142606244511569936384000000000
Prelude> fac_l 3
6
----

=== Functions

==== Single results

* using a single parameter
+
[source,haskell]
.A function that calculates the square of an integer
----
Prelude> let square x = x * x
Prelude> square 42
1764
Prelude>
----
+
[source,haskell]
.A function that calculates the factorial of a natural number
----
Prelude> let fact n = product [1..n]
Prelude> fact 5
120
Prelude> fact 10
3628800
Prelude>
----

* using multiple parameters
+
[source,haskell]
.add_2arg_int.hs
----
add :: Integer -> Integer -> Integer
add x y = x + y
main = do
    print(add 42 13)
----

* using strings
+
[source,haskell]
.src/ghci/combine_strings.hs
----
combine_strings :: String -> String -> String
combine_strings s1 s2 = s1 ++ s2
----
+
[source,console]
----
$ ghci src/ghci/combine_strings.hs
----
+
[source,haskell]
.src/ghci/combine_strings.hs
----
*Main> combine_strings "hello" " world"
"hello world"
----

* using tuple
+
[source,haskell]
----
add :: (Integer, Integer) -> Integer
add (x, y) = x + y
main = do
    print(add(42, 13))
----

==== Multiple results

* An example of a use of tuples
+
[source,haskell]
.src/ghci/swap.hs
----
swap :: (String, String) -> (String, String)
swap (a, b) = (b, a)
main = do
    let (a, b) = swap ("hello", "world")
    putStrLn (a ++ " " ++ b)
----
+
[source,console]
----
$ ghci src/ghci/swap.hs
----
+
[source,haskell]
.Results
----
*Main> main
world hello
*Main> swap("hello", "world")
("world","hello")
*Main> swap(swap("hello", "world"))
("hello","world")
*Main> (swap . swap)("hello", "world")
("hello","world")
*Main> swap $ swap("hello", "world")
("hello","world")
----

* Single integer to list of integers 
+
[source,haskell]
.src/ghci/func_int_to_list.hs
----
get_int_list :: Int -> [Int]
get_int_list n = [n] ++ [n]
main = do
    print(get_int_list 3)
----
+
[source,console]
----
$ ghci src/ghci/func_int_to_list.hs
----
+
[source,haskell]
----
*Main> main
[3,3]
*Main> get_int_list 4
[4,4]
----

==== Recursion

* Collatz map
+
[source,haskell]
----
collatz :: Integer -> [Integer]
collatz n | n == 1         = [1]
          | n `mod` 2 == 0 = [n] ++ collatz (n `div` 2)
          | n `mod` 2 == 1 = [n] ++ collatz (n * 3 + 1)
----
+
[source,console]
----
$ ghci src/ghci/collatz.hs
----
+
[source,haskell]
----
*Main> collatz 3
[3,10,5,16,8,4,2,1]
----

==== Higher-order function

* using arguments
+
[source,haskell]
.higher_order_args.hs
----
compute :: (Double -> Double -> Double) -> Double
compute f = f 3 4 ::Double

main = do
    let hypot = \x y -> sqrt (x^2 + y^2)
    print $ hypot 5 12
    print $ compute hypot
    print $ compute (**)
----
+
.Results
----
13.0
5.0
81.0
----

* using tuple and a anonymous function
+
[source,haskell]
.higher_order_tuple.hs
----
compute :: ((Double, Double) -> Double) -> Double
compute (f) = f (3::Double, 4::Double)

main = do
    let hypot = \(x, y) -> sqrt (x^2 + y^2)
    print $ hypot(5, 12)
    print $ compute(hypot)
    print $ compute((\(x, y) -> x**y))
----
+
.Results
----
13.0
5.0
81.0
----

* using tuple and a named function
+
[source,haskell]
----
compute :: ((Double, Double) -> Double) -> Double
compute (f) = f (3::Double, 4::Double)

hypot :: (Double, Double) -> Double
hypot (x, y) = sqrt (x^2 + y^2)

main = do
    print $ hypot(5, 12)
    print $ compute(hypot)
    print $ compute((\(x, y) -> x**y))
----
+
.Results
----
13.0
5.0
81.0
----

===== Map

[source,haskell]
----
Prelude> map (\n -> n + 1) [1,2,3]
[2,3,4]
----

===== Composing functions (合成)

[source,haskell]
----
Prelude> ((+ 1) . (* 2)) 3
7
Prelude> (+ 1) $ (* 2) 3
7
Prelude>
----

=== Monad

[source,haskell]
----
Prelude> Just 1 >>= \x -> return (x*2)
Just 2
Prelude> Nothing >>= \x -> return (x*2)
Nothing
Prelude> [1,2,3] >>= \x -> return (x * 2)
[2,4,6]
Prelude>
----

=== Math

[source,haskell]
.abs
----
*Main> abs (-1)
1
*Main>
----

[source,haskell]
----
*Main> 1254 `div` 1000
1
*Main> 1254 `rem` 1000
254
*Main> 
----

[source,haskell]
.`mod`
----
*Main> (-4) `mod` 3
2
*Main> (-1) `mod` 3
2
*Main>
----

[source,haskell]
.`rem`
----
*Main> (-4) `rem` 3
-1
*Main> (-1) `rem` 3
-1
*Main>
----

==== Sum

* sum
+
[source,haskell]
----
Prelude> :set +s
Prelude> sum [1..1000000]
500000500000
(0.88 secs, 161,299,720 bytes)
Prelude> sum [1..1000000]
500000500000
(0.69 secs, 161,299,720 bytes)
Prelude> sum [1..1000000]
500000500000
(0.72 secs, 161,299,720 bytes)
Prelude> sum [1..1000000]
500000500000
(0.73 secs, 161,300,296 bytes)
Prelude> sum [1..1000000]
500000500000
(0.64 secs, 161,299,144 bytes)
----

* sum'
+
[source,haskell]
----
Prelude> let sum'(x:xs) = x + sum(xs)
Prelude> :set +s
Prelude> sum' [1..1000000]
500000500000
(0.53 secs, 161,299,344 bytes)
Prelude> sum' [1..1000000]
500000500000
(0.67 secs, 161,299,344 bytes)
Prelude> sum' [1..1000000]
500000500000
(0.56 secs, 161,299,344 bytes)
Prelude> sum' [1..1000000]
500000500000
(0.64 secs, 161,299,344 bytes)
Prelude> sum' [1..1000000]
500000500000
(0.72 secs, 161,297,672 bytes)
----

* foldr
+
[source,haskell]
----
Prelude> :set +s
Prelude> foldr (+) 0 [1..1000000]
500000500000
(0.50 secs, 161,589,312 bytes)
Prelude> foldr (+) 0 [1..1000000]
500000500000
(0.52 secs, 161,589,224 bytes)
Prelude> foldr (+) 0 [1..1000000]
500000500000
(0.41 secs, 161,590,416 bytes)
Prelude> foldr (+) 0 [1..1000000]
500000500000
(0.56 secs, 161,589,400 bytes)
Prelude> foldr (+) 0 [1..1000000]
500000500000
(0.64 secs, 161,590,416 bytes)
Prelude> foldl (+) 0 [1..1000000]
500000500000
(0.59 secs, 161,298,944 bytes)
----

* sum'
+
[source,haskell]
----
Prelude> :set +s
Prelude> foldl (+) 0 [1..1000000]
500000500000
(0.59 secs, 161,298,944 bytes)
Prelude> foldl (+) 0 [1..1000000]
500000500000
(0.72 secs, 161,297,312 bytes)
Prelude> foldl (+) 0 [1..1000000]
500000500000
(0.72 secs, 161,297,312 bytes)
Prelude> foldl (+) 0 [1..1000000]
500000500000
(0.66 secs, 161,297,312 bytes)
Prelude> foldl (+) 0 [1..1000000]
500000500000
(0.67 secs, 161,297,312 bytes)
----

==== Prime number


* determining whether an input number is prime
+
[source,haskell]
----
isPrime k = if k > 1 then null [ x | x <- [2..k - 1], k `mod` x == 0] else False
----

* Prime numbers up to 100
+
[source,haskell]
----
Prelude> [ n | n <- [2..100], null [k | k <- [2..(n-1)], n `mod` k == 0]]
[2,3,5,7,11,13,17,19,23,29,31,37,41,43,47,53,59,61,67,71,73,79,83,89,97]
Prelude> length [ n | n <- [2..100], null [k | k <- [2..(n-1)], n `mod` k == 0]]
25
----

* Taking the first 25 primes from an infinite list
+
[source,haskell]
----
Prelude> take 25 [ n | n <- [2..], null [x | x <- [2..(n-1)], n `mod` x == 0]]
[2,3,5,7,11,13,17,19,23,29,31,37,41,43,47,53,59,61,67,71,73,79,83,89,97]
Prelude> length $ take 25 [ n | n <- [2..], null [x | x <- [2..(n-1)], n `mod` x == 0]]
25
----
+
[source,haskell]
----
Prelude> factors x = filter (\y -> x `mod` y == 0) [1..x]
Prelude> primes = [ x | x <- [1..], factors x == [1,x] ]
Prelude> take 25 primes
[2,3,5,7,11,13,17,19,23,29,31,37,41,43,47,53,59,61,67,71,73,79,83,89,97]
----
+
[source,haskell]
----
Prelude> take 25 $ [2..] >>= \n -> if null ([2..(n-1)] >>= \k -> if n `mod` k == 0 then [k] else []) then [n] else []
[2,3,5,7,11,13,17,19,23,29,31,37,41,43,47,53,59,61,67,71,73,79,83,89,97]
----
