ifndef::leveloffset[]
:toc: left
:toclevels: 3
:icons: font
endif::[]

include::header.adoc[]

== Haskell examples

=== ghci

[source,console]
----
$ ghci
GHCi, version 8.0.2: http://www.haskell.org/ghc/  :? for help
----

=== Type annotations

==== same types

[source,haskell]
----
Prelude> (+) 2 3 ::Double
5.0
----

==== different types

[source,haskell]
----
add_int_and_float :: Integer -> Float -> Float
add_int_and_float x y = fromIntegral(x) + y
main = do
    print(add_int_and_float 1 1.5)
----

.Results
* No type annotations
+
[source,haskell]
----
*Main> add_int_and_float 3 4.5
7.5
----

* NG: Both add type annotations as Integer
+
[source,haskell]
----
*Main> add_int_and_float 3 4.5 :: Integer

<interactive>:3:1: error:
    • Couldn't match expected type ‘Integer’ with actual type ‘Float’
    • In the expression: add_int_and_float 3 4.5 :: Integer
      In an equation for ‘it’: it = add_int_and_float 3 4.5 :: Integer
----

* Add type annotations as Float to right parameter
+
[source,haskell]
----
*Main> add_int_and_float 3 (4.5::Float)
7.5
----

* Add different type annotations to both variables
+
[source,haskell]
----
*Main> add_int_and_float (3::Integer) (4.5::Float)
7.5
----

=== Various types

==== String

===== Concatenate vector of chars into single string


* Chars
+
[source,haskell]
----
Prelude> ['a', 'b', 'c']
"abc"
----

* Using the colon(`:`) operator to prepend chars
+
[source,haskell]
----
Prelude> 'a':'b':'c':[]
"abc"
----

===== Concatenate vector of strings into single string

* Using `(++)`
+
[source,haskell]
----
Prelude> :t (++)
(++) :: [a] -> [a] -> [a]
Prelude> "abc" ++ "123" ++ "cdf"
"abc123cdf"
Prelude>
----

* Using `concat`
+
[source,haskell]
----
Prelude> :t concat
concat :: Foldable t => t [a] -> [a]
Prelude> concat ["abc", "123", "cdf"]
"abc123cdf"
Prelude>
----

* Using `Control.Monad.join`
+
[source,haskell]
----
Prelude> Control.Monad.join ["abc", "123", "cdf"]
"abc123cdf"
----
+
[source,haskell]
----
Prelude> import Control.Monad
Prelude Control.Monad> join ["abc", "123", "cdf"]
"abc123cdf"
Prelude Control.Monad>
----

* You can also use the list monad to reduce the list to a single string, then re-wrap the result in a list.
+
[source,haskell]
----
Prelude> ["abc", "123", "cdf"] >>= id
"abc123cdf"
Prelude>
----

* using `foldr` and `foldl`
+
[source,haskell]
----
Prelude> foldr (\s_prepend s -> s_prepend ++ s) "" ["abc", "123", "cdf"]
"abc123cdf"
Prelude> foldl (\s s_add -> s ++ s_add) "" ["abc", "123", "cdf"]
"abc123cdf"
----

===== Join strings with a delimiter

* Using `Data.List.intercalate`
+
[source,haskell]
----
Prelude> Data.List.intercalate ", " ["John", "Due"]
"John, Due"
----
+
[source,haskell]
----
Prelude> import Data.List
Prelude Data.List> intercalate ", " ["John", "Due"]
"John, Due"
Prelude Data.List>
----

==== Composite Types

===== Vertex

* No field name
+
[source,haskell]
.src/data-types/composite-types/ex1_no_named_fields/vertex_deriving_show.hs
----
include::../src/data-types/composite-types/ex1_no_named_fields/vertex_deriving_show.hs[]
----
+
[source,console]
----
$ ghci src/data-types/composite-types/ex1_no_named_fields/vertex_deriving_show.hs
----
+
+
[source,haskell]
----
*Main> :show modules
Main             ( src/data-types/composite-types/ex1_no_named_fields/vertex_deriving_show.hs, interpreted )
*Main> :info Vertex
data Vertex = Vertex Int Int
        -- Defined at src/data-types/composite-types/ex1_no_named_fields/vertex_deriving_show.hs:1:1
instance [safe] Show Vertex
  -- Defined at src/data-types/composite-types/ex1_no_named_fields/vertex_deriving_show.hs:1:40
*Main> :t Vertex
Vertex :: Int -> Int -> Vertex
*Main> a = Vertex 3 4
*Main> a
Vertex 3 4
*Main> (\(Vertex x _) -> x) a
3
*Main> (\(Main.Vertex x _) -> x) a
3
*Main> (\(Vertex _ y) -> y) a
4
*Main> (\(Vertex x y) -> sqrt(fromIntegral (x*x + y*y))) a
5.0
*Main> main
Vertex 3 4
3
3
4
5.0
Vertex 2 3
----

** Implement show
+
[source,haskell]
.src/data-types/composite-types/ex1_no_named_fields/vertex_impl_show.hs
----
include::../src/data-types/composite-types/ex1_no_named_fields/vertex_impl_show.hs[]
----
+
[source,console]
----
$ ghci src/data-types/composite-types/ex1_no_named_fields/vertex_impl_show.hs
----
+
[source,haskell]
----
*Main> print $ Vertex 3 4
Vertex 3 4
*Main> main
Vertex 3 4
3
3
4
5.0
Vertex 2 3
----

* With filed name
+
[source,haskell]
.src/data-types/composite-types/ex2_named_fields/Euclidean2D.hs
----
include::../src/data-types/composite-types/ex2_named_fields/Euclidean2D.hs[]
----
+
[source,haskell]
.src/data-types/composite-types/ex2_named_fields/Main.hs
----
include::../src/data-types/composite-types/ex2_named_fields/Main.hs[]
----
+
[source,console]
----
$ cd src/data-types/composite-types/ex2_named_fields/
$ ghci Main.hs
----

** Show modules
+
[source,haskell]
----
*Main> :show modules
Euclidean2D      ( Euclidean2D.hs, interpreted )
Main             ( Main.hs, interpreted )
----
+
[source,console]
----
*Main> :info Vertex
data Vertex = Vertex {x :: Int, y :: Int}
        -- Defined at Euclidean2D.hs:2:1
instance [safe] Show Vertex -- Defined at Euclidean2D.hs:3:10
*Main> :t Vertex
Vertex :: Int -> Int -> Vertex
*Main> :t x
x :: Vertex -> Int
*Main> :info x
data Vertex = Vertex {x :: Int, ...}
        -- Defined at Euclidean2D.hs:2:24
*Main> :t y
y :: Vertex -> Int
*Main> :info y
data Vertex = Vertex {..., y :: Int}
        -- Defined at Euclidean2D.hs:2:34
----

** Use Vertex
+
[source,haskell]
----
*Main> a = Vertex { x = 3, y = 4 }
*Main> a
Vertex {x=3,y=4}
*Main> x a
3
*Main> Euclidean2D.x a
3
*Main> (\v -> sqrt ( fromIntegral (x v * x v + y v * y v) )) a
5.0
*Main> (\v -> sqrt ( fromIntegral (x v * x v + y v * y v) )) (Vertex 5 12)
13.0
----

** Run main
+
[source,haskell]
----
*Main> main
Vertex {x=3,y=4}
3
3
4
5.0
----

==== Enum

* Enum to Int
+
[source,haskell]
.src/classes/enum_to_int.hs
----
include::../src/classes/enum_to_int.hs[]
----
+
[source,console]
----
$ ghci src/classes/enum_to_int.hs
----
+
[source,haskell]
----
*Main> main
0
1
2
[0,1,2]
----

* Int to enum
+
[source,haskell]
.src/classes/int_to_enum.hs
----
include::../src/classes/int_to_enum.hs[]
----
+
[source,console]
----
$ ghci src/classes/int_to_enum.hs
----
+
[source,haskell]
----
*Main> main
Apple
Orange
Kiwi
[Apple,Orange,Kiwi]
*Main> :t (map toEnum [0, 1, 2] :: [Fruits])
(map toEnum [0, 1, 2] :: [Fruits]) :: [Fruits]
----

===== Matching enum

* Using pattern matching
+
[source,haskell]
.src/classes/enum_pattern_matching.hs
----
include::../src/classes/enum_pattern_matching.hs[]
----
+
[source,console]
----
$ ghci src/classes/enum_pattern_matching.hs
----
+
[source,haskell]
----
*Main> main
Apple: I like apples.
Orange: I like oranges.
Kiwi: I like kiwis.
----

* Using case expressions
+
[source,haskell]
.src/classes/enum_case_of.hs
----
include::../src/classes/enum_case_of.hs[]
----
+
[source,console]
----
$ ghci src/classes/enum_case_of.hs
----
+
[source,haskell]
----
*Main> main
Apple: I like apples.
Orange: I like oranges.
Kiwi: I like kiwis.
----

* Using where bindings
+
[source,haskell]
.src/classes/enum_where_binding.hs
----
include::../src/classes/enum_where_binding.hs[]
----
+
[source,console]
----
$ ghci src/classes/enum_where_binding.hs
----
+
[source,haskell]
----
*Main> main
Apple: I like apples.
Orange: I like oranges.
Kiwi: I like kiwis.
----

==== List

* Make a list
+
[source,haskell]
----
Prelude> [1, 2, 3]
[1,2,3]
Prelude> :t []
[] :: [t]
----
+
[source,haskell]
.Using the colon operator
----
Prelude> 1:2:3:[]
[1,2,3]
Prelude> :t (:)
(:) :: a -> [a] -> [a]
----

* Prepend the item to the list
+
.Using the colon operator. colon is the "prepend" operator
[source,haskell]
----
Prelude> 1:2:3:[]
[1,2,3]
Prelude> "apple":"banana":"cherry":["durian"]
["apple","banana","cherry","durian"]
----
+
[source,haskell]
----
Prelude> (:) 1 []
[1]
Prelude> (:) 1 ((:) 2 ((:) 3 []))
[1,2,3]
Prelude> (:) 1 $ (:) 2 $ (:) 3 []
[1,2,3]
Prelude> ((:) 1 . (:) 2 . (:) 3) []
[1,2,3]
----

* Returns the first item of a list
+
[source,haskell]
.Using `head`
----
Prelude> head []
*** Exception: Prelude.head: empty list
Prelude> head [1, 2, 3]
1
Prelude> head [1..]
1
----
+
[source,haskell]
----
Prelude> let head' (h:_) = h
Prelude> :t head'
head' :: [t] -> t
Prelude> head' []
*** Exception: <interactive>:61:5-19: Non-exhaustive patterns in function head'

Prelude> head' [1, 2, 3]
1
Prelude> head' [1..]
1
Prelude> head' ["apple", "banana", "cherry", "durian"]
"apple"
----
+
[source,haskell]
.Using `take`
----
Prelude> take 1 []
[]
Prelude> take 1 [1, 2, 3]
[1]
Prelude> take 3 [1..]
[1,2,3]
----
+
[source,haskell]
.Using `foldr`
----
Prelude> foldr (\x _ -> [x]) [] []
[]
Prelude> foldr (\x _ -> [x]) [] [1, 2, 3]
[1]
Prelude> foldr (\x _ -> [x]) [] [1..]
[1]
Prelude> foldr (\s _ -> [s]) [] []
[]
Prelude> foldr (\s _ -> [s]) [] ["apple", "banana", "cherry", "durian"]
["apple"]
----

* returns the last item of a list
+
[source,haskell]
.Using `last`
----
Prelude> last [1, 2, 3]
3
----
+
[source,haskell]
.Using `foldl`
----
Prelude> foldl (\_ x -> x) 0 [1, 2, 3]
3
----

* it accepts a list and returns the list without its last item
+
[source,haskell]
----
Prelude> init [1, 2, 3]
[1,2]
----

* it accepts a list and returns the list without its first item
+
[source,haskell]
----
Prelude> tail ["A", "B", "C"]
["B","C"]
Prelude> drop 1 ["A", "B", "C"]
["B","C"]
----
+
[source,haskell]
----
Prelude> let tail' (_:t) = t
Prelude> :t tail'
tail' :: [t] -> [t]
Prelude> tail' []
*** Exception: <interactive>:67:5-19: Non-exhaustive patterns in function tail'

Prelude> tail' ["A", "B", "C"]
["B","C"]
----

* The length of a list
+
[source,haskell]
----
Prelude> :t length
length :: Foldable t => t a -> Int
Prelude> length ["apple", "banana", "cherry", "durian"]
4
----
+
[source,haskell]
.The length of a list without the "length" function in Haskell
----
Prelude> foldr (\_ n -> n + 1) 0 ["apple", "banana", "cherry", "durian"]
4
----

* Reverse a list in haskell
+
[source,haskell]
----
Prelude> reverse ["apple","banana","cherry"]
["cherry","banana","apple"]
----
+
[source,haskell]
----
Prelude> foldr (\x xs -> xs ++ [x]) [] ["apple", "banana", "cherry"]
["cherry","banana","apple"]
----

* Combine two lists
+
[source,haskell]
----
Prelude> [1, 2, 3] ++ [4, 5, 6]
[1,2,3,4,5,6]
----


* Program to left rotate a list
+
[source,haskell]
----
Prelude> let rotate_l a = tail a ++ take 1 a
Prelude> :t rotate_l
rotate_l :: [a] -> [a]
Prelude> rotate_l [1, 2, 3]
[2,3,1]
Prelude> rotate_l $ rotate_l [1, 2, 3]
[3,1,2]
Prelude> rotate_l $ rotate_l $ rotate_l [1, 2, 3]
[1,2,3]
----

* Program to right rotate a list
+
[source,haskell]
----
Prelude> let rotate_r a = [last a] ++ init a
Prelude> :t rotate_r
rotate_r :: [a] -> [a]
Prelude> rotate_r [1, 2, 3]
[3,1,2]
Prelude> rotate_r $ rotate_r [1, 2, 3]
[2,3,1]
Prelude> rotate_r $ rotate_r $ rotate_r [1, 2, 3]
[1,2,3]
Prelude> rotate_l $ rotate_r [1, 2, 3]
[1,2,3]
----

===== List comprehension (リストの内包表記)

* Filter multiples of 3 from a List
+
[source,haskell]
----
Prelude> [p | p <- [1..10], p `mod` 3 == 0]
[3,6,9]
Prelude> filter (\x -> x `mod` 3 == 0) [1..10]
[3,6,9]
Prelude> [1..10] >>= \x -> if x `mod` 3 == 0 then pure x else []
[3,6,9]
Prelude> [1..10] >>= \x -> if x `mod` 3 == 0 then x:[] else []
[3,6,9]
Prelude> [1..10] >>= \x -> if x `mod` 3 == 0 then [x] else []
[3,6,9]
----
+
[source,haskell]
.Using infinite lists
----
Prelude> take 3 [p | p <- [1..], p `mod` 3 == 0]
[3,6,9]
Prelude> take 3 $ filter (\x -> x `mod` 3 == 0) [1..]
[3,6,9]
Prelude> take 3 $ [1..] >>= \x -> if x `mod` 3 == 0 then pure x else []
[3,6,9]
----

* Making a list of divisors in Haskell
+
[source,haskell]
----
Prelude> [x | x <- [2..9], 10 `mod` x == 0]
[2,5]
Prelude> filter (\x -> 10 `mod` x == 0) [2..9]
[2,5]
Prelude> [2..9] >>= \x -> if 10 `mod` x == 0 then pure x else []
[2,5]
----

* Find cubic root of a number
+
[source,haskell]
----
Prelude> [x | x <- [2..7], x * x * x == 8]
[2]
Prelude> filter (\x -> x * x * x == 8) [2..7]
[2]
Prelude> [2..7] >>= \x -> if x * x * x == 8 then pure x else []
[2]
----
+
[source,haskell]
.Using infinite lists
----
Prelude> take 1 $ [x | x <- [2..], x * x * x == 8]
[2]
Prelude> take 1 $ filter (\x -> x * x * x == 8) [2..]
[2]
Prelude> take 1 $ [2..] >>= \x -> if x * x * x == 8 then pure x else []
[2]
----

* Combining two lists
+
[source,haskell]
----
Prelude> [(x,y) | x <- [1,2], y <- [1,2,3]]
[(1,1),(1,2),(1,3),(2,1),(2,2),(2,3)]
----

===== Infinite lists

* Make infinite lists
+
[source,haskell]
----
Prelude> a = 1:a
Prelude> take 3 a
[1,1,1]
Prelude> take 10 [2,4..]
[2,4,6,8,10,12,14,16,18,20]
----
+
[source,haskell]
----
Prelude> take 6 ([2, 3] ++ a)
[2,3,1,1,1,1]
----
+
[source,haskell]
----
Prelude> c = 1:[x * 2 | x <- c]
Prelude> take 10 c
[1,2,4,8,16,32,64,128,256,512]
----

* Gets the first one element from the infinite list.
+
[source,haskell]
----
Prelude> head [1..]
1
----

* Takeing the first three elements from the infinite list.
+
[source,haskell]
----
Prelude> take 3 [1..]
[1,2,3]
----

* Determine if there is an element that meets the conditions in the infinite list.
+
[source,haskell]
----
Prelude> :set +s
Prelude> null [x | x <- [1..], x == 1]
False
(0.00 secs, 64,016 bytes)
Prelude> null [x | x <- [1..], x == 100000]
False
(0.05 secs, 8,865,312 bytes)
----

* Add one
+
[source,haskell]
----
Prelude> take 10 $ map (+ 1) [1..]
[2,3,4,5,6,7,8,9,10,11]
Prelude> take 10 [ x + 1 | x <- [1..] ]
[2,3,4,5,6,7,8,9,10,11]
----


==== Tuples

* fst and snd
+
[source,haskell]
----
Prelude> fst(1, 2)
1
Prelude> snd(1, 2)
2
----

* swap
+
[source,haskell]
----
Prelude> import Data.Tuple
Prelude Data.Tuple> swap("hello", "world")
("world","hello")
Prelude Data.Tuple> swap $ swap("hello", "world")
("hello","world")
Prelude Data.Tuple> (swap . swap)("hello", "world")
("hello","world")
----

[source,haskell]
----
Prelude> curry fst "hello" "world"
"hello"
Prelude> uncurry div (10, 5)
2
Prelude>
----

=== Flow control statements

==== Loop using counter

* not using using guards
+
[source,haskell]
.loop_counter_no_guards.hs
----
main = do
    let loop 6 = return ()
        loop i = do
            print i
            loop (i + 1)
    loop 1
----
+
[source,haskell]
----
*Main> :load src/ghci/loop_counter_no_guards.hs
[1 of 1] Compiling Main             ( src/ghci/loop_counter_no_guards.hs, interpreted )
Ok, modules loaded: Main.
*Main> main
1
2
3
4
5
*Main>
----

* using guards
+
[source,haskell]
.loop_counter_using_guards.hs
----
main = do
    let loop i
          | i <= 5 = do
              print i
              loop (i + 1)
          | otherwise = return ()
    loop 1
----
+
[source,haskell]
----
*Main> :load src/ghci/loop_counter_using_guards.hs
[1 of 1] Compiling Main             ( src/ghci/loop_counter_using_guards.hs, interpreted )
Ok, modules loaded: Main.
*Main> main
1
2
3
4
5
*Main>
----

* loop 1 million
+
[source,haskell]
----
import Data.Time.Clock

main = do
    let sum_1million total
          | total < 10^6 = do
              sum_1million (total + 1)
          | otherwise = return total
    t0 <- getCurrentTime
    sum_1million 0 >>= print
    t1 <- getCurrentTime
    print (t1 `diffUTCTime` t0)
----
+
[source,haskell]
----
Prelude> :load src/ghci/loop_1million.hs
[1 of 1] Compiling Main             ( src/ghci/loop_1million.hs, interpreted )
Ok, modules loaded: Main.
*Main> main
1000000
3.0136357s
----
+
[source,console]
.No optimization: compiled with no flags with ghc
----
$ ../../bin/loop_1million
1000000
1.5058498s
----
+
[source,console]
.compiled with `-O2` flags with ghc
----
$ ../../bin/loop_1million
1000000
0.023587s
----
+
[NOTE]
Rust ではデバッグモードで 32ms, リリースビルドで 2µs ぐらい。
+
.References
* https://github.com/nh2/loop[Fast loops for Haskell (for when GHC can't optimize ... - GitHub^]
* https://www.channable.com/tech/how-we-made-haskell-search-strings-as-fast-as-rust[How we made Haskell search strings as fast as Rust^]

==== Loop using range

[source,haskell]
.loop_using_range.hs
----
main = do
    let loop is_true i n
          | is_true == True = do
              print i
              loop ((i + 1) < n) (i + 1) n
          | is_true /= True = return ()
    loop (1 < 6) 1 6
----

[source,haskell]
----
*Main> :load src/ghci/loop_using_range.hs
[1 of 1] Compiling Main             ( src/ghci/loop_using_range.hs, interpreted )
Ok, modules loaded: Main.
*Main> main
1
2
3
4
5
*Main>
----

==== Condition
[source,haskell]
----
Prelude> fact 5 == 120
True
Prelude>
----

==== Recursion

===== Reverse

[source,haskell]
.src/recursion/reverse.hs
----
include::../src/recursion/reverse.hs[]
----

[source,haskell]
.Results
----
*Main> reverse' "abc"
"cba"
----

===== Quicksort

[source,haskell]
.src/recursion/quicksort.hs
----
include::../src/recursion/quicksort.hs[]
----

[source,haskell]
.Results
----
*Main> quicksort [6, 1, 1, 8, 6, 5, 3, 7, 2, 1, 4, 3, 8, 9]
[1,1,1,2,3,3,4,5,6,6,7,8,8,9]
*Main> quicksort "I have a pen."
"   .Iaaeehnpv"
*Main> quicksort ["Orange", "Apple", "Kiwi", "Banana", "Peach", "Watermelon"]
["Apple","Banana","Kiwi","Orange","Peach","Watermelon"]
----

===== Factorial

* Implement recursion using recursive calls
+
[source,haskell]
.src/math/fac.hs
----
include::../src/math/fac.hs[]
----
+
[source,haskell]
----
*Main> :set +s
*Main> fac_p 42
1405006117752879898543142606244511569936384000000000
(0.02 secs, 129,936 bytes)
*Main> fac_g 42
1405006117752879898543142606244511569936384000000000
(0.02 secs, 132,320 bytes)
*Main> fac_if_then_else 42
1405006117752879898543142606244511569936384000000000
(0.02 secs, 132,312 bytes)
----

* Implement recursion using `foldr` in haskell
+
[source,haskell]
----
Prelude> let fac_r n = foldr (*) 1 [1..n]
Prelude> fac_r 42
1405006117752879898543142606244511569936384000000000
Prelude> fac_r 3
6
----

* Implement recursion using `foldl` in haskell
+
[source,haskell]
----
Prelude> let fac_l n = foldl (*) 1 [1..n]
Prelude> fac_l 42
1405006117752879898543142606244511569936384000000000
Prelude> fac_l 3
6
----

===== Fibonacci sequence

[source,haskell]
.src/math/fib.hs
----
include::../src/math/fib.hs[]
----

===== Collatz map

* Collatz map
+
[source,haskell]
.src/math/collatz_with_guards.hs
----
include::../src/math/collatz_with_guards.hs[]
----
+
[source,haskell]
.src/math/collatz_with_pattern.hs
----
include::../src/math/collatz_with_pattern.hs[]
----

** Run
+
[source,console]
----
$ ghci src/math/collatz_with_guards.hs
----
+
[source,haskell]
----
*Main> collatz 3
[3,10,5,16,8,4,2,1]
----

=== Functions

==== using a single parameter

* Using integers

** Omit types
+
[source,haskell]
.A function that calculates the square of an integer
----
Prelude> let square x = x * x
Prelude> square 42
1764
Prelude>
----
+
[source,haskell]
.A function that calculates the factorial of a natural number
----
Prelude> let fact n = product [1..n]
Prelude> fact 5
120
Prelude> fact 10
3628800
Prelude>
----

* Using Floating type class +
Floating is a type class.
+
[source,haskell]
----
Prelude> pi :: Float
3.1415927
Prelude> pi :: Double
3.141592653589793
----
+
[source,haskell]
.src/functions/circle_area.hs
----
include::../src/functions/circle_area.hs[]
----
+
[source,console]
.Run ghci
----
$ ghci src/functions/circle_area.hs
----
+
[source,haskell]
.Results
----
*Main> :t circle_area_float
circle_area_float :: Float -> Float
*Main> circle_area_float 1
3.1415927
*Main> :t circle_area_double
circle_area_double :: Double -> Double
*Main> circle_area_double 1
3.141592653589793
*Main> circle_area_floating 1 :: Float
3.1415927
*Main> circle_area_floating 1 :: Double
3.141592653589793
----

* Using Real, etc
+
[source,haskell]
.src/math/squared.hs
----
include::../src/math/squared.hs[]
----

** Integer
+
[source,haskell]
.3037000499^2
----
*Main> sqInt 3037000499
9223372030926249001
*Main> sqInteger 3037000499
9223372030926249001
*Main> sqIntegral 3037000499::Int
9223372030926249001
----
+
[source,haskell]
.3037000500^2 - Int
----
*Main> sqInt 3037000500
-9223372036709301616
*Main> sqIntegral 3037000500::Int
-9223372036709301616
----
+
[source,haskell]
.3037000500^2 - Integer
----
*Main> sqInteger  3037000500
9223372037000250000
*Main> sqIntegral 3037000500::Integer
9223372037000250000
----

** Floating
+
[source,haskell]
.sqrt(2) - Float
----
*Main> sqFloat (sqrt(2)::Float)
1.9999999
*Main> sqFloating (sqrt(2)::Float)
1.9999999
*Main> sqFractional (sqrt(2)::Float)
1.9999999
*Main> sqReal (sqrt(2)::Float)
1.9999999
*Main> sqRealFrac (sqrt(2)::Float)
1.9999999
*Main> sqRealFloat (sqrt(2)::Float)
1.9999999
*Main> sqNum (sqrt(2)::Float)
1.9999999
*Main> sqComplex ((sqrt(2)::Float) :+ 0)
1.9999999 :+ 0.0
----
+
[source,haskell]
.sqrt(2) - Double
----
*Main> sqDouble (sqrt(2)::Double)
2.0000000000000004
*Main> sqFloating (sqrt(2)::Double)
2.0000000000000004
*Main> sqFractional (sqrt(2)::Double)
2.0000000000000004
*Main> sqReal (sqrt(2)::Double)
2.0000000000000004
*Main> sqRealFrac (sqrt(2)::Double)
2.0000000000000004
*Main> sqRealFloat (sqrt(2)::Double)
2.0000000000000004
*Main> sqNum (sqrt(2)::Double)
2.0000000000000004
*Main> sqComplex ((sqrt(2)::Double) :+ 0)
2.0000000000000004 :+ 0.0
----

** Rational
+
[source,haskell]
.Rational
----
*Main> sqFractional (1/3 :: Rational)
1 % 9
*Main> sqRealFrac (1/3 :: Rational)
1 % 9
*Main> sqReal (1/3 :: Rational)
1 % 9
*Main> sqNum (1/3 :: Rational)
1 % 9
----

** Complex numbers
+
[source,haskell]
.Complex numbers
----
*Main> sqComplex (0 :+ 1)
(-1.0) :+ 0.0
*Main> sqFractional (0 :+ 1)
(-1.0) :+ 0.0
*Main> sqNum (0 :+ 1)
(-1.0) :+ 0.0
----

==== Multiple parameters

* Using Int
+
[source,haskell]
.add_2arg_int.hs
----
include::../src/functions/add_2arg_int.hs[]
----
+
[source,haskell]
----
*Main> add 42 13
55
*Main> add 42.0 13.0

<interactive>:3:5: error:
    • No instance for (Fractional Int) arising from the literal ‘42.0’
    • In the first argument of ‘add’, namely ‘42.0’
      In the expression: add 42.0 13.0
      In an equation for ‘it’: it = add 42.0 13.0
*Main> add (maxBound :: Int) 0
9223372036854775807
*Main> add (maxBound :: Int) 1
-9223372036854775808
*Main> add (minBound :: Int) (0)
-9223372036854775808
*Main> add (minBound :: Int) (-1)
9223372036854775807
----

* Using Num
+
[source,haskell]
.add_2arg_num.hs
----
include::../src/functions/add_2arg_num.hs[]
----

** Add variable types
+
[source,haskell]
----
*Main> add (42 :: Int) 13
55
*Main> add (42 :: Integer) 13
55
*Main> add (42 :: Rational) 13
55 % 1
*Main> add 42.0 13.0
55.0
*Main> add (42 :: Float) 13
55.0
*Main> add (42 :: Double) 13
55.0
----

** Overflow & underflow
+
[source,haskell]
.NG: Int
----
*Main> add (maxBound :: Int) 1
-922337203685477580
*Main> add (minBound :: Int) (-1)
9223372036854775807
----
+
[source,haskell]
.OK: Integer
----
*Main> add (toInteger (maxBound :: Int)) 1
9223372036854775808
*Main> add (toInteger (minBound :: Int)) (-1)
-9223372036854775809
----

* using strings
+
[source,haskell]
.src/data-types/string/combine_strings.hs
----
include::../src/data-types/string/combine_strings.hs[]
----
+
[source,console]
----
$ ghci src/data-types/string/combine_strings.hs
----
+
[source,haskell]
.src/data-types/string/combine_strings.hs
----
*Main> combine_strings "hello" " world"
"hello world"
----

* using tuple
+
[source,haskell]
.src/functions/add_2arg_tuple.hs
----
include::../src/functions/add_2arg_tuple.hs[]
----

* using list

** XOR
+
[source,haskell]
.src/functions/xor.hs
----
include::../src/functions/xor.hs[]
----
+
[source,haskell]
----
*Main> xor ([] :: [Int])
DEBUG[]
[]
*Main> xor ([1, 1, 1] :: [Int])
DEBUG(1:1:[1])
DEBUG(0:1:[])
DEBUG[1]
[1]
*Main> xor ([1, 1, 1, 1] :: [Int])
DEBUG(1:1:[1,1])
DEBUG(0:1:[1])
DEBUG(1:1:[])
DEBUG[0]
[0]
----

** Remove the second element
+
[source,haskell]
.src/functions/remove_2nd_element.hs
----
include::../src/functions/remove_2nd_element.hs[]
----
+
[source,haskell]
.Results
----
*Main> remove2ndElement ([] :: [Int])
[]
*Main> remove2ndElement [1]
[1]
*Main> remove2ndElement [1, 2]
[1]
*Main> remove2ndElement [1, 2, 3]
[1,3]
*Main> remove2ndElement [1, 2, 3, 4]
[1,3,4]
----

==== Multiple results

* An example of a use of tuples
+
[source,haskell]
.src/ghci/swap.hs
----
swap :: (String, String) -> (String, String)
swap (a, b) = (b, a)
main = do
    let (a, b) = swap ("hello", "world")
    putStrLn (a ++ " " ++ b)
----
+
[source,console]
----
$ ghci src/ghci/swap.hs
----
+
[source,haskell]
.Results
----
*Main> main
world hello
*Main> swap("hello", "world")
("world","hello")
*Main> swap(swap("hello", "world"))
("hello","world")
*Main> (swap . swap)("hello", "world")
("hello","world")
*Main> swap $ swap("hello", "world")
("hello","world")
----

* Single integer to list of integers 
+
[source,haskell]
.src/functions/func_int_to_list.hs
----
include::../src/functions/func_int_to_list.hs[]
----
+
[source,console]
----
$ ghci src/functions/func_int_to_list.hs
----
+
[source,haskell]
----
*Main> main
[3,3]
*Main> get_int_list 4
[4,4]
----

* Various types
+
[source,haskell]
----
include::../src/functions/make_tuple_various_types.hs[]
----
+
[source,console]
----
$ ghci src/functions/make_tuple_various_types.hs
----
+
[source,haskell]
.Results
----
*Main> main
(3,1 % 3,3.14,"hello")
(3,1 % 3,3.14,"world")
----

==== Order

[source,haskell]
.src/functions/max_num.hs
----
include::../src/functions/max_num.hs[]
----

.Results
* max_num
+
[source,haskell]
----
*Main> max_num (3 :: Int) 4
4
*Main> max_num (pi::Float) (sqrt(2)::Float)
3.1415927
*Main> max_num (pi::Double) (sqrt(2)::Double)
3.141592653589793
*Main> max_num (1/3 ::Rational) 1/2
1 % 2
----

* max_gen
+
[source,haskell]
----
*Main> max_gen (3 :: Int) 4
4
*Main> max_gen (pi::Float) (sqrt(2)::Float)
3.1415927
*Main> max_gen (pi::Double) (sqrt(2)::Double)
3.141592653589793
*Main> max_gen (1/3 ::Rational) 1/2
1 % 2
*Main> max_gen True False
True
*Main> max_gen 'z' 'a'
'z'
*Main> max_gen "apple" "kiwi"
"kiwi"
----

==== Eq

[source,haskell]
----
include::../src/functions/eq.hs[]
----

[source,haskell]
----
*Main> eq (3 :: Int) 3
True
*Main> eq (1/3 :: Rational) (1/3 :: Rational)
True
*Main> eq (pi::Float) 3.1415927
True
*Main> eq (pi::Double) 3.141592653589793
True
*Main> eq False False
True
*Main> eq 'a' 'a'
True
*Main> eq "hello" "hello"
True
----

==== Higher-order function

* using arguments
+
[source,haskell]
.higher_order_args.hs
----
include::../src/functions/higher_order_args.hs[]
----
+
.Results
----
13.0
5.0
81.0
----

* using tuple and a anonymous function
+
[source,haskell]
.higher_order_tuple.hs
----
include::../src/functions/higher_order_tuple.hs[]
----
+
.Results
----
13.0
5.0
81.0
----

* using tuple and a named function
+
[source,haskell]
----
compute :: ((Double, Double) -> Double) -> Double
compute (f) = f (3::Double, 4::Double)

hypot :: (Double, Double) -> Double
hypot (x, y) = sqrt (x^2 + y^2)

main = do
    print $ hypot(5, 12)
    print $ compute(hypot)
    print $ compute((\(x, y) -> x**y))
----
+
.Results
----
13.0
5.0
81.0
----

===== Map

[source,haskell]
----
Prelude> map (\n -> n + 1) [1,2,3]
[2,3,4]
----

===== Composing functions (合成)

[source,haskell]
----
Prelude> ((+ 1) . (* 2)) 3
7
Prelude> (+ 1) $ (* 2) 3
7
Prelude>
----

=== Monad

[source,haskell]
----
Prelude> Just 1 >>= \x -> return (x*2)
Just 2
Prelude> Nothing >>= \x -> return (x*2)
Nothing
Prelude> [1,2,3] >>= \x -> return (x * 2)
[2,4,6]
Prelude>
----
