ifndef::leveloffset[]
:toc: left
:toclevels: 3
:icons: font
endif::[]

ifndef::leveloffset[]
include::header.adoc[]
endif::[]

== Char & String

=== Covert to integer

* Id
+
[source,haskell]
.Using Data.Char
----
> import Data.Char
> (chr . ord) 'a'
'a'
----
+
[source,haskell]
.Using Enum
----
> (toEnum . fromEnum) 'a' :: Char
'a'
----

* Get Int value
+
[source,haskell]
.Using Data.Char
----
> import Data.Char (chr, ord)
> ord 'a'
97
> chr 97
'a'
----
+
[source,haskell]
.Using Enum
----
> fromEnum 'a'
97
> toEnum 97 :: Char
'a'
----

* Increment / decrement
+
[source,haskell]
.Using Data.Char
----
Prelude> import Data.Char (chr, ord)
Prelude Data.Char> (chr . (+ 1) . ord) 'a'
'b'
Prelude Data.Char> (chr . (+ (-1)) . ord) 'z'
'y'
----
+
[source,haskell]
.Using Data.Char
----
Prelude> :m + Data.Char
Prelude Data.Char> chr (ord 'a' + 1)
'b'
Prelude Data.Char> chr (ord 'z' - 1)
'y'
----
+
[source,haskell]
.Using Enum
----
Prelude> :m + Data.Char
Prelude Data.Char> (toEnum . (+1) . fromEnum) 'a' :: Char
'b'
Prelude Data.Char> (toEnum . (+ (-1)) . fromEnum) 'z' :: Char
'y'
----
+
[source,haskell]
.Using Enum
----
Prelude> :m + Data.Char
Prelude Data.Char> toEnum $ (fromEnum 'a' + 1) :: Char
'b'
Prelude Data.Char> toEnum $ (fromEnum 'z' - 1) :: Char
'y'
----

* Check letter case
+
[source,haskell]
.src/data-types/string/check_case.hs
----
include::../src/data-types/string/check_case.hs[]
----

=== Read from String

[source,haskell]
----
Prelude> read "123" :: Int
123
Prelude> read "123" :: Double
123.0
Prelude> read "[1, 2, 3]" :: [Int]
[1,2,3]
Prelude> read "[1, 3.141592, NaN, Infinity, -Infinity, 3.1e5, 3.1e-4]" :: [Double]
[1.0,3.141592,NaN,Infinity,-Infinity,310000.0,3.1e-4]
Prelude> read "(1, 'a')" :: (Int, Char)
(1,'a')
----

* Date/Time

** Date
+
[source,haskell]
----
Prelude> :m + Data.Time.Calendar
Prelude Data.Time.Calendar> read "2019-08-31" :: Day
2019-08-31
----

** Time
+
[source,haskell]
----
Prelude> :m + Data.Time
Prelude Data.Time> read "2019-08-31" :: Day
2019-08-31
Prelude Data.Time> read "12:12:31" :: TimeOfDay
12:12:31
Prelude Data.Time> read "2019-08-31 12:12:31" :: UTCTime
2019-08-31 12:12:31 UTC
Prelude Data.Time> read "2019-08-31 12:12:31.123456" :: UTCTime
2019-08-31 12:12:31.123456 UTC
Prelude Data.Time> read "2019-08-31 12:12:31.123456Z" :: UTCTime
2019-08-31 12:12:31.123456 UTC
Prelude Data.Time> read "2019-08-31 12:12:31.123456" :: LocalTime
2019-08-31 12:12:31.123456
Prelude Data.Time> read "2019-08-31 12:12:31.123456+09:00" :: ZonedTime
2019-08-31 12:12:31.123456 +0900
----

=== Concatenate vector of chars into single string

* Chars
+
[source,haskell]
----
Prelude> ['a', 'b', 'c']
"abc"
----

* Using the colon(`:`) operator to prepend chars
+
[source,haskell]
----
Prelude> 'a':'b':'c':[]
"abc"
----

=== Concatenate vector of strings into single string

* Using `(++)`
+
[source,haskell]
----
Prelude> :t (++)
(++) :: [a] -> [a] -> [a]
Prelude> "abc" ++ "123" ++ "cdf"
"abc123cdf"
Prelude>
----

* Using `concat`
+
[source,haskell]
----
Prelude> :t concat
concat :: Foldable t => t [a] -> [a]
Prelude> concat ["abc", "123", "cdf"]
"abc123cdf"
Prelude>
----

* Using `Control.Monad.join`
+
[source,haskell]
----
Prelude> Control.Monad.join ["abc", "123", "cdf"]
"abc123cdf"
----
+
[source,haskell]
----
Prelude> import Control.Monad
Prelude Control.Monad> join ["abc", "123", "cdf"]
"abc123cdf"
Prelude Control.Monad>
----

* You can also use the list monad to reduce the list to a single string, then re-wrap the result in a list.
+
[source,haskell]
----
Prelude> ["abc", "123", "cdf"] >>= id
"abc123cdf"
Prelude>
----

* using `foldr` and `foldl`
+
[source,haskell]
----
Prelude> foldr (\s_prepend s -> s_prepend ++ s) "" ["abc", "123", "cdf"]
"abc123cdf"
Prelude> foldl (\s s_add -> s ++ s_add) "" ["abc", "123", "cdf"]
"abc123cdf"
----

=== Join strings with a delimiter

* Using `Data.List.intercalate`
+
[source,haskell]
----
Prelude> Data.List.intercalate ", " ["John", "Due"]
"John, Due"
----
+
[source,haskell]
----
Prelude> import Data.List
Prelude Data.List> intercalate ", " ["John", "Due"]
"John, Due"
Prelude Data.List>
----

=== word / unwords

[source,haskell]
----
Prelude> words "foo bar baz"
["foo","bar","baz"]
Prelude> unwords ["foo","bar","baz"]
"foo bar baz"
Prelude> lines "hello\nworld"
["hello","world"]
Prelude> unlines ["hello","world"]
"hello\nworld\n"
----

=== ROT13

* Without `mod`
+
[source,haskell]
.src/data-types/string/rot13_decoder_1.hs
----
include::../src/data-types/string/rot13_decoder_1.hs[]
----

* Using `mod`
+
[source,haskell]
.src/data-types/string/rot13_decoder_2.hs
----
include::../src/data-types/string/rot13_decoder_2.hs[]
----

* Using table
+
[source,haskell]
.src/data-types/string/rot13_decoder_3.hs
----
include::../src/data-types/string/rot13_decoder_3.hs[]
----

[source,haskell]
.Results
----
*Main> decodeRot13 ""
""
*Main> decodeRot13 "Lbh penpxrq gur pbqr!"
"You cracked the code!"
----

=== IO

[source,haskell]
----
Prelude> writeFile "temp.txt" $ show [1,2,3]
Prelude> readFile "temp.txt"
"[1,2,3]"
Prelude> do {cs <- readFile "temp.txt"; return (read cs :: [Int])}
[1,2,3]
----

[source,haskell]
----
Prelude> writeFile "temp.txt" $ unlines $ map show [1,2,3,4,5]
Prelude> readFile "temp.txt"
"1\n2\n3\n4\n5\n"
Prelude> do cs <- readFile "temp.txt"; return $ map (\x->read x :: Int) $ lines cs
[1,2,3,4,5]
----
