.PHONY: digits_sum_has_nth_roots factorial loop_1million

clean:
	(cd digits_sum_has_nth_roots && make $@)
	(cd factorial && make $@)
	(cd loop_1million && make $@)

distclean:
	(cd digits_sum_has_nth_roots && make $@)
	(cd factorial && make $@)
	(cd loop_1million && make $@)
