.PHONY: digits_sum_has_nth_roots math/factorial loop_1million

clean:
	(cd digits_sum_has_nth_roots && make $@)
	(cd math && make $@)
	(cd loop_1million && make $@)

distclean:
	(cd digits_sum_has_nth_roots && make $@)
	(cd math && make $@)
	(cd loop_1million && make $@)
