.PHONY: digits_sum_has_nth_roots functions loop_1million math

clean:
	(cd digits_sum_has_nth_roots && make $@)
	(cd functions && make $@)
	(cd math && make $@)
	(cd loop_1million && make $@)

distclean:
	(cd digits_sum_has_nth_roots && make $@)
	(cd functions && make $@)
	(cd math && make $@)
	(cd loop_1million && make $@)
